"""Stable-key UI catalogs. Scientific terminology is intentionally untranslated."""

EN = {
    "menu.file": "&File", "menu.tags": "&Tags", "menu.processing": "&Processing",
    "menu.interfaces": "Interfaces",
    "menu.settings": "&Settings", "menu.view": "&View", "menu.analysis": "&Analysis",
    "action.open_database": "&Open Database...", "action.reload_database": "&Reload Database",
    "action.exit": "E&xit", "action.manage_tags": "&Manage Tags...",
    "action.retrieve_tags": "&Retrieve by Tags...", "action.debackground": "De-background...",
    "action.settings": "Settings...", "action.measurement": "Measurement",
    "action.time_domain": "Time Domain", "action.online_paper_library": "Online Paper Library",
    "action.open": "&Open...", "action.reload": "&Reload",
    "action.open_data_table": "Data Table", "action.metadata": "Metadata",
    "action.traces": "&Traces", "action.show": "Show", "action.export": "Export",
    "action.cancel": "Cancel", "action.save": "Save", "action.delete": "Delete",
    "action.rename": "Rename", "action.search": "Search", "action.add": "Add",
    "browser.no_database": "No database open. File → Open Database to begin.",
    "browser.open_database": "Open Database...", "browser.reload_database": "Reload Database",
    "browser.star": "Star", "browser.unstar": "Unstar", "browser.tag": "Tag...",
    "browser.star_column": "Star", "browser.star_cell_starred": "Starred · click to Unstar",
    "browser.star_cell_unstarred": "Not starred · click to Star",
    "browser.glass_thickness": "Thickness", "browser.glass_frost": "Frost",
    "browser.glass_thickness_tip": "Glass thickness: refraction depth and rim highlight",
    "browser.glass_frost_tip": "Glass frost: blur and milky haze",
    "browser.glass_unavailable": "Glass effect is off (Safe Recovery or LABLOGVIEWER_DISABLE_GLASS)",
    "viewer.restore_layout": "Restore Layout",
    "browser.retrieve_by_tags": "Retrieve by Tags...", "browser.back_to_folder": "Back to Folder",
    "browser.folders": "Folders", "browser.tags_selected": "Tags of Selected Data",
    "browser.data_folder": "Data in Folder", "browser.edit_tags": "Edit Tags...",
    "browser.no_data_selected": "No Data selected", "browser.no_tags": "No tags",
    "browser.tags_none": "Tags: none", "browser.log_name": "Log name",
    "browser.date_created": "Date created", "browser.sweep_dimension": "Sweep dimension",
    "browser.source_folder": "Source folder", "browser.tags": "Tags",
    "browser.quick_preview": "Quick Preview", "browser.comment": "Comment",
    "browser.select_tags": "Select Tags", "browser.match": "Match", "browser.recent": "Recent",
    "browser.clear_recent": "Clear Recent", "browser.retrieve": "Retrieve",
    "settings.general": "General", "settings.appearance": "Appearance",
    "settings.debug": "Debug", "settings.about": "About",
    "settings.language": "Language", "settings.title": "Settings",
    "theme.light": "Light", "theme.dark": "Dark", "theme.system": "Follow System",
    "settings.advanced": "Advanced", "settings.scientific_plot_appearance": "Scientific Plot Appearance",
    "settings.export_plot_background": "Export Plot Background",
    "settings.appearance_menu": "Appearance...", "settings.theme": "Theme",
    "settings.glass": "Toolbar Glass",
    "settings.three_d": "3D", "settings.three_d_menu": "3D...",
    "three_d.open": "Open HDF5...",
    "net.address": "Or address:",
    "net.address_placeholder": "Host IP (e.g. 192.168.1.20 or 192.168.1.20:47811)",
    "net.address_tip": "Use this when automatic search finds nothing (some networks block it).",
    "net.firewall_notice": "Windows will now ask whether LabLogViewer may accept connections. Choose \"Private networks\" and click Allow; otherwise other computers cannot join.",
    "settings.cloud_blocked": "This folder is synced by {service}. History records (stars, tags, marks, sessions, analysis records) are not allowed in cloud-synced folders: sync can move files off this computer or create conflicting copies, and records can be lost.",
    "settings.cloud_consent": "I understand: if history records are lost, I am responsible; the developer has no right or ability to recover them.",
    "settings.cloud_move_anyway": "Move anyway",
    "settings.cloud_current": "Warning: the data folder is synced by {service}. Move it to a local folder to keep history records safe.",
    "settings.personal": "Personal",
    "personal.colors": "Colours",
    "personal.icons": "Icons",
    "personal.item": "Item",
    "personal.code": "Colour code",
    "personal.reset_one": "Reset colour",
    "personal.reset_group": "Reset group",
    "personal.reset_all": "Reset all colours",
    "personal.group_app_light": "Light theme",
    "personal.group_app_dark": "Dark theme",
    "personal.group_plot_white": "Scientific plot — white",
    "personal.group_plot_dark": "Scientific plot — dark",
    "personal.group_pens": "Annotation pens",
    "personal.low_contrast": "{group}: {fg} on {bg} is hard to read (contrast {ratio:.1f}, 3.0 or more recommended).",
    "personal.icons_note": "Replace any icon with your own SVG file (plain SVG only: no scripts, links or embedded images; up to 256 KB). Your file is copied; the original icon is kept.",
    "personal.locked": "Personal colours unlock after 10 data operations (Marks, transforms, zoom, fits ... on different measurement files). {remaining} to go. Icons can be changed now.",
    "personal.unlocked": "Personal colours are unlocked.",
    "personal.unlocked_license": "Personal colours are unlocked by a licence until {date}.",
    "license.open": "Licences...", "license.title": "Licences",
    "license.intro": "A licence file (.llvkey) from the developer unlocks features on one computer. To ask for one, send the machine code below. Licences are valid for a limited time (usually two months) and can be requested again.",
    "license.machine_code": "Machine code:", "license.copy": "Copy",
    "license.holder": "Holder", "license.features": "Features", "license.expires": "Valid until", "license.status": "Status",
    "license.install": "Install Licence...", "license.remove": "Remove",
    "license.valid_days": "Valid ({days} days left)", "license.installed": "The licence is installed.",
    "license.feature_personal_colors": "Personal colours", "license.feature_relink": "Re-link moved data",
    "license.feature_migrate": "Data transfer", "migrate.open": "Data Transfer...",
    "license.error_format": "Not a LabLogViewer licence file.",
    "license.error_signature": "The licence signature is invalid (the file was changed or not issued by the developer).",
    "license.error_machine": "This licence is for another computer.",
    "license.error_expired": "This licence has expired; ask the developer for a new one.",
    "license.error_no_key": "This copy of LabLogViewer cannot check licences (no developer key installed).",
    "license.program": "This program: LabLogViewer {version} — {folder}",
    "settings.app_icon": "App icon", "settings.app_icon_n": "Icon {n}",
    "settings.auto_refresh": "Auto refresh (new and changed measurements)",
    "settings.auto_refresh_off": "Off", "settings.auto_refresh_n": "Every {n} s",
    "settings.auto_refresh_tip": "Checks file sizes and times only (cheap, also on shared storage); only new or changed files are read again. An open Viewer follows a running measurement.",
    "browser.auto_refresh_done": "Auto refresh: {added} new, {changed} changed, {removed} removed",
    "action.new_folder": "&New Folder...", "browser.new_folder": "New Folder...",
    "browser.new_folder_title": "New Folder", "browser.new_folder_prompt": "Name of the new folder in {parent}:",
    "browser.new_folder_empty": "Type a name for the folder.",
    "browser.new_folder_bad": "A folder name cannot contain / \\ : * ? \" < > |, start with a dot, or end with a space or a dot.",
    "browser.new_folder_exists": "\"{name}\" already exists here.",
    "browser.new_folder_failed": "The folder could not be created: {reason}",
    "browser.new_folder_done": "Folder created: {name}",
    "whatsnew.title": "What's New in LabLogViewer {version}", "whatsnew.open": "What's New...",
    "whatsnew.heading": "LabLogViewer {version}", "whatsnew.updated": "Updated from {old} to {new}",
    "whatsnew.earlier": "an earlier version", "whatsnew.none": "No notes for this version.",
    "whatsnew.newer_title": "Please update LabLogViewer",
    "whatsnew.newer_data": "Your records were written by a newer LabLogViewer. This older version leaves them unchanged, but some newer records may not show. Please install the newest version.",
    "whatsnew.upgrade_failed_title": "Records not upgraded",
    "whatsnew.upgrade_failed": "Adapting your records to this version failed; they were put back as they were (a backup is in update_backups in the data folder). Reason: {reason}",
    "license.key_ok": "Developer public key: installed ({key})",
    "license.key_missing": "Developer public key: not installed — licences cannot be checked by this copy",
    "license.key_where": "The public key must be installed in this folder:\n{folder}\n(licence generator: choose this LabLogViewer folder, then generate once).",
    "license.error_clock": "This computer's date is earlier than the licence's issue date; check the clock.",
    "relink.open": "Re-link Moved Data...", "relink.title": "Re-link Moved Data",
    "relink.intro": "Records (stars, tags, comments, Marks, views, 3D views, YIG sessions) belong to the path where a file was. If files were moved, choose the folder they are in now and press Find Files (found by content, works after renaming), or, if only the folder or NAS mount changed, pick the old folder and press Match by Path (quick). Their records are then moved to the new paths. The record files are backed up first and the change can be undone. Measurement files are only read.",
    "relink.missing": "{count} old paths have records but no file ({fingerprinted} with a content fingerprint).",
    "relink.new_folder": "Folder with the moved files:", "relink.browse": "Browse...", "relink.search": "Find Files",
    "relink.old_path": "Old path", "relink.new_path": "Found at", "relink.match": "Match", "relink.records": "Records",
    "relink.conf_exact": "Same content", "relink.conf_guess": "Same name and size (check)", "relink.not_found": "Not found",
    "relink.guess_note": "\"Same content\" rows are ticked. \"Same name and size\" rows had no fingerprint to compare; tick them only if you are sure.",
    "relink.apply": "Re-link Ticked Rows", "relink.undo": "Undo Last Re-link",
    "relink.close_viewers": "Close all Viewer windows first.",
    "relink.confirm": "Move the records of {count} files to their new paths? The record files are backed up first.",
    "relink.done": "Re-linked {count} files. Backup: {backup}", "relink.conflicts": "Kept the records already at the new path (you chose to keep them):",
    "relink.undo_confirm": "Put back the records as they were before the last re-link? Changes made to those records since then are lost.",
    "relink.undone": "The last re-link was undone.",
    "save.exists_title": "A file with this name exists", "save.exists_text": "\"{name}\" already exists in\n{folder}",
    "save.exists_info": "Overwrite replaces it. Keep Both saves the new one as \"{new_name}\".",
    "save.exists_no_replace": "It cannot be replaced from here. Keep Both uses \"{new_name}\" instead.",
    "save.overwrite": "Overwrite", "save.keep_both": "Keep Both", "save.choose_another": "Choose Another…",
    "save.cancel": "Cancel",
    "relink.old_folder": "Old folder (quick, by path):", "relink.by_path": "Match by Path",
    "relink.by_path_tip": "Use when the files kept their place inside a folder that moved or a share that now mounts under another name: the old folder part of each path is replaced by the folder above. Only names and sizes are checked, nothing is read, so it is quick on a NAS.",
    "relink.conf_path": "Same place, same size",
    "relink.conflict_question": "{count} records exist under both the old and the new path, made by you, and differ (see Details). Records the program made by itself at the new path (automatic Tags, first view) are replaced by your old ones without asking.\n\nWhich should be kept for these {count}?",
    "relink.use_old": "Overwrite with Old Records", "relink.keep_new": "Keep Current Records",
    "settings.tag_root": "Largest data folder (Tag search)",
    "settings.tag_root_note": "The one big folder where all measurements are collected. Retrieve by Tags can search it instead of only the open database. It searches LabLogViewer's Tag records (fast even for millions of files), so files are found once a database containing them has been opened. Automatic Tags are only given to files at most 4 folders below the opened database.",
    "settings.tag_root_browse": "Browse...", "settings.tag_root_clear": "Clear", "settings.tag_root_none": "Not set",
    "fig.menu": "Scientific Figure Builder...", "fig.title": "Scientific Figure Builder",
    "fig.crashed": "The Figure Builder closed unexpectedly ({reason}). The rest of LabLogViewer is not affected; open it again from Processing.",
    "fig.open_dxf": "Open DXF...", "fig.open_project": "Open Figure...", "fig.save_project": "Save Figure...",
    "fig.add_yig": "Add YIG", "fig.add_coil": "Add Coil", "fig.add_wave": "Add Sine Wave", "fig.delete": "Delete",
    "fig.undo": "Undo", "fig.redo": "Redo", "fig.export_pptx": "Export PowerPoint...", "fig.export_image": "Export Image...",
    "fig.layers": "Layers", "fig.selection": "Selected", "fig.view": "View",
    "fig.empty": "Open a DXF drawing (AutoCAD 2013).\nLayers: b, g, h (microstrip) or db, ub, g, h, v (coplanar waveguide).",
    "fig.col_show": "Show", "fig.col_layer": "Layer", "fig.col_color": "Colour", "fig.col_thickness": "Thickness",
    "fig.col_place": "Placement", "fig.layer_up": "Move Up", "fig.layer_down": "Move Down",
    "fig.place_stack": "On layer below", "fig.place_same": "Same level", "fig.place_through": "Through all",
    "fig.mode_ms": "Mode: microstrip (MS)", "fig.mode_cpw": "Mode: coplanar waveguide (CPW)",
    "fig.elevation": "Elevation", "fig.azimuth": "Rotation", "fig.background": "Background",
    "fig.no_selection": "Click a YIG, coil or sine wave to edit it.\nDrag empty space to turn the view.",
    "fig.yig_radius": "Radius (mm)", "fig.yig_lift": "Height above surface (mm)", "fig.yig_spins": "Spin arrows",
    "fig.yig_color": "Sphere colour", "fig.yig_spin_color": "Spin colour",
    "fig.coil_radius": "Radius (mm)", "fig.coil_wire": "Wire thickness (mm)", "fig.coil_turns": "Turns",
    "fig.coil_pitch": "Turn spacing (mm)", "fig.coil_gap": "Gap under board (mm)", "fig.coil_color": "Colour",
    "fig.coil_arrow": "Field arrow", "fig.coil_arrow_color": "Arrow colour",
    "fig.wave_cycles": "Cycles", "fig.wave_phase": "Phase (deg)", "fig.wave_width": "Line width (pt)",
    "fig.wave_dashed": "Dashed", "fig.wave_color": "Colour",
    "personal.follow_theme": "Follow theme colour (recolour the SVG for light / dark)",
    "personal.replace_icon": "Replace with SVG...",
    "personal.restore_icon": "Restore default",
    "personal.restore_all_icons": "Restore all icons",
    "personal.svg_rejected": "This SVG cannot be used: {reason}",
    "personal.field_window": "Window background",
    "personal.field_panel": "Panels",
    "personal.field_alternate": "Alternate rows / hover",
    "personal.field_text": "Text",
    "personal.field_secondary": "Secondary text",
    "personal.field_border": "Borders",
    "personal.field_accent": "Accent",
    "personal.field_selected": "Selection",
    "personal.field_plot_background": "Plot background",
    "personal.field_plot_panel": "Plot panel",
    "personal.field_control": "Buttons / controls",
    "personal.field_input": "Input fields",
    "personal.field_background": "Background",
    "personal.field_red": "Red pen",
    "personal.field_blue": "Blue pen",
    "personal.field_yellow": "Yellow pen",
    "personal.field_green": "Green pen",
    "personal.field_laser": "Laser pointer",
    "interaction.zoom": "Zoom",
    "interaction.zoom_tip": "Zoom: drag a rectangle with the left button; right-click or Esc steps back.",
    "help.title": "LabLogViewer Help",
    "help.search": "Search help",
    "help.export_ai": "Export for AI...",
    "help.include_state": "Include what is open now (version, system, windows; no data, paths or user names)",
    "help.save_file": "Save file...",
    "help.copy_text": "Copy text",
    "net.title": "Network Workspace",
    "net.host": "Host",
    "net.client": "Client",
    "net.rename": "Rename...",
    "net.this_computer": "This computer: {name}",
    "net.name_title": "Name this computer",
    "net.name_prompt": "Name shown to others in the Network Workspace (any language):",
    "net.session": "Workspace / Session",
    "net.session_placeholder": "e.g. Tuesday group meeting",
    "net.status": "Status",
    "net.join_code": "Join code",
    "net.sharing": "Sharing",
    "net.clients": "Connected Clients",
    "net.send_copy": "Send a permanent copy...",
    "net.send_copy_tip": "Only the Host can give a Client a saved copy of the current measurement.",
    "net.send_copy_confirm": "Send a permanent copy of the current HDF5 file to {name}? It will be saved on that computer.",
    "net.start_hosting": "Start Hosting",
    "net.stop_hosting": "Stop Hosting",
    "net.cannot_host": "Hosting cannot start: {reason}",
    "net.hosting": "Hosting · {count} / 5 Clients",
    "net.not_hosting": "Not hosting",
    "net.open_viewer": "Open a measurement in a Viewer to share it.",
    "net.search_placeholder": "Search host name or session name",
    "net.search": "Search",
    "net.searching": "Searching this network...",
    "net.found": "{count} Host(s) found.",
    "net.none_found": "No Host found. Try the search again, or check that both computers are on the same network.",
    "net.host_row": "{host} — {session}  ({clients}/{max})",
    "net.host_info": "Host / Workspace",
    "net.shared_folders": "Shared data folders...",
    "net.shared_folders_tip": "If this computer can read the same files (e.g. shared storage), they are used instead of downloading.",
    "net.shared_folders_list": "Shared data folders: {folders}",
    "net.none": "none",
    "net.connect": "Connect",
    "net.disconnect": "Disconnect",
    "net.pick_host": "Select a Host first.",
    "net.offline": "Offline",
    "net.leave": "Leave",
    "net.following": "Following {host} · {session} (view only)",
    "net.source_local": "data: this computer",
    "net.source_host": "data: from Host (memory only)",
    "net.mirror_title": "{name} — following {host} (view only)",
    "net.yig_mirror_title": "YIG Analysis — following {host} — {title}",
    "net.receiving_structure": "Receiving the measurement structure...",
    "net.receiving_data": "Receiving data",
    "net.transfer_failed": "Transfer failed: {reason}",
    "net.host_in_3d": "The Host is looking at a 3D view, which is not shared.",
    "net.copy_failed": "The copy from the Host failed its checksum and was discarded.",
    "net.copy_received": "The Host sent you a permanent copy, saved to:\n{path}",
    "net.state_connecting": "Connecting",
    "net.state_connected": "Connected",
    "net.state_reconnecting": "Reconnecting",
    "net.state_disconnected": "Disconnected",
    "net.level_excellent": "Excellent",
    "net.level_good": "Good",
    "net.level_fair": "Fair",
    "net.level_unusable": "Too poor",
    "net.level_unknown": "Measuring",
    "net.reason_wrong_code": "wrong join code",
    "net.reason_host_full": "the Host already has 5 Clients",
    "net.reason_not_same_subnet": "the computers are not on the same network",
    "net.reason_poor_quality": "network quality is below the minimum (200 ms, 1 MB/s)",
    "net.reason_host_unavailable": "Host unavailable",
    "net.reason_host_closed": "the Host stopped hosting",
    "net.reason_timeout": "timed out",
    "net.reason_left": "you left",
    "net.reason_protocol_mismatch": "different LabLogViewer network versions",
    "net.reason_too_many_attempts": "too many wrong codes; wait a minute",
    "three_d.crash_title": "3D window closed",
    "three_d.crash_text": "The 3D Surface window stopped unexpectedly (it runs in its own process, often because of the graphics driver). The rest of LabLogViewer is not affected and nothing was lost.",
    "three_d.reopen": "Reopen 3D",
    "trust.title": "Trust this model file?",
    "trust.intro": "{name} is Python code. Loading it runs it with your permissions, so only trust model files you wrote or got from someone you trust. Review the code below. You are asked once; if the file changes you will be asked again.",
    "trust.warnings": "Please check:", "trust.trust": "Trust and Load",
    "settings.data_folder": "Data Folder", "settings.data_folder_current": "Location",
    "settings.data_folder_browse": "Change Location...", "settings.data_folder_open": "Show Folder",
    "settings.data_folder_default": "Use Default",
    "settings.data_folder_choose": "Choose where to keep the LabLogViewerData folder",
    "settings.data_folder_tip": "Stars, tags, comments, marks, transforms, sessions and analysis records. Measured values in HDF5 files are never modified (a comment may be written to Labber's own comment field).",
    "settings.data_folder_pending": "Will move at next launch to",
    "settings.data_folder_occupied": "{path} already contains LabLogViewer data.\n\nUse the data in that folder? Your current folder is left unchanged.",
    "settings.data_folder_restart": "The data folder changes the next time LabLogViewer starts (all records are moved then).\n\nQuit LabLogViewer now?",
    "settings.three_d_profile": "3D Performance", "settings.profile_balanced": "Balanced",
    "settings.profile_quality": "High Quality", "settings.profile_economy": "Resource Saving",
    "settings.three_d_profile_tip": "Display vertex budgets for 3D surfaces; source data is never changed.",
    "settings.white_background": "White Background", "settings.dark_background": "Dark Background",
    "language.english": "English", "language.traditional_chinese": "中文（繁體）",
    "language.english_name": "English", "language.chinese_name": "Traditional Chinese",
    "viewer.plot_mode": "Plot Mode:", "viewer.one_d": "1D Plot", "viewer.two_d": "2D Heatmap",
    "viewer.nd": "3D Surface", "viewer.maximize": "Maximize Plot",
    "viewer.nd_visualization": "N-D Visualization:", "viewer.nd_heatmap": "2D Heatmap",
    "viewer.surface_3d": "3D Surface", "viewer.reset_view": "Reset View",
    "viewer.view_all": "View All",
    "viewer.surface_sampling": "Display sampling: {source_rows} × {source_columns} → {rows} × {columns} vertices. Scientific data is unchanged.",
    "viewer.surface_gaps": "{count} non-finite Z values shown as gaps.",
    "viewer.surface_error": "3D Surface unavailable: {reason}",
    "viewer.axis_x": "X", "viewer.axis_y": "Y", "viewer.height_z": "Height (Z)",
    "viewer.transform": "Transform", "viewer.surface": "SURFACE", "viewer.color": "COLOR",
    "viewer.rendering": "Rendering", "viewer.policy_auto": "Auto",
    "viewer.policy_full": "Full Resolution", "viewer.policy_adaptive": "Adaptive LOD",
    "viewer.policy_performance": "Performance", "viewer.z_scale": "Z Scale",
    "viewer.z_scale_range": "Visual vertical scale (0.1x to 10x)",
    "viewer.auto": "Auto", "viewer.reset_z_scale": "Reset Z Scale",
    "viewer.projection": "Projection", "viewer.perspective": "Perspective",
    "viewer.orthographic": "Orthographic", "viewer.color_source": "Color Source",
    "viewer.same_as_height": "Same as Height", "viewer.colormap": "Colormap",
    "viewer.minimum": "Minimum", "viewer.maximum": "Maximum",
    "viewer.auto_range": "Auto Range", "viewer.camera": "CAMERA",
    "viewer.camera_top": "Top", "viewer.camera_front": "Front",
    "viewer.camera_side": "Side", "viewer.camera_isometric": "Isometric",
    "viewer.geometry_type": "Geometry Type",
    "viewer.opacity": "Opacity",
    "viewer.transparency": "Transparency",
    "viewer.surface_a_opacity": "Surface A Opacity",
    "viewer.surface_b_mapping": "Surface B Mapping",
    "viewer.surface_b_opacity": "Surface B Opacity",
    "viewer.plane_value": "Plane Value",
    "viewer.point_color": "Point Color",
    "viewer.point_size_3d": "Point Size",
    "viewer.point_x": "Point X",
    "viewer.point_y": "Point Y",
    "viewer.point_z": "Point Z",
    "viewer.reference_plane": "Reference Plane",
    "viewer.unwrap_along": "Unwrap Along",
    "viewer.along_x": "Along X",
    "viewer.along_y": "Along Y",
    "viewer.bottom_projection": "Bottom Projection",
    "viewer.top_colorbar": "Top Interactive Colorbar",
    "viewer.reference_off": "Off",
    "viewer.reference_custom_mode": "Custom",
    "viewer.zero_plane": "Zero Plane",
    "viewer.surface_3d_menu": "3D Surface...",
    "annotation.toggle": "Annotation",
    "annotation.pen": "Pen",
    "annotation.laser": "Laser Pointer",
    "annotation.clear": "Clear Screen",
    "annotation.width": "Width",
    "annotation.trail": "Trail",
    "annotation.red": "Red",
    "annotation.blue": "Blue",
    "annotation.yellow": "Yellow",
    "annotation.green": "Green",
    "viewer.copy_3d": "Copy 3D Plot",
    "viewer.save_3d": "Save 3D Plot...",
    "viewer.copied_3d": "3D plot copied.",
    "viewer.export_style_publication": "Export: Publication style",
    "viewer.export_style_screen": "Export: Screen capture",
    "settings.three_d_export_style": "3D Export Style",
    "settings.export_style_publication": "Publication (journal figure)",
    "settings.export_style_screen": "Screen capture",
    "settings.three_d_export_style_tip": "Publication renders a journal-style figure (PNG/PDF/SVG); Screen captures the interactive view.",
    "viewer.advanced": "Advanced", "viewer.slice_dimensions": "Slice Dimensions",
    "viewer.no_second_dimension": "No second dimension",
    "viewer.surface_select_data": "Select a Data source to build a Surface.",
    "viewer.surface_needs_xy": "Choose distinct X and Y dimensions to build a 3D Surface.",
    "viewer.surface_loading": "Preparing scientific Surface…",
    "viewer.surface_single_pane": "3D Surface is available in a single Viewer pane.",
    "viewer.surface_large_warning": "Large grid: reduced interactive mesh; Full Resolution remains available.",
    "viewer.surface_grid_status": "Grid {source_rows} × {source_columns}; {vertices} rendered vertices; {policy}.",
    "viewer.surface_performance": "{fps:.1f} FPS ({frame_ms:.1f} ms/frame)",
    "viewer.reference_outside": "Reference plane {value} is outside the height range {low} … {high}.",
    "viewer.reference_minimum": "Minimum plane: {value}", "viewer.reference_zero": "Zero plane: {value}",
    "viewer.reference_custom": "Reference plane: {value}",
    "viewer.waterfall_traces": "{count} trace ribbons",
    "viewer.surface_pick_hint": "Left-drag: Rotate  ·  Middle-drag: Pan  ·  Wheel: Zoom  ·  Left-click: Read scientific values",
    "viewer.surface_performance_details": "Source {source_rows} × {source_columns}; render {render_rows} × {render_columns} ({vertices} vertices); {policy}.",
    "viewer.transparent_status": "Transparent Surface · {vertices:,} display samples / {source:,} source samples",
    "viewer.transparent_full_limit": "Transparent Full Resolution is limited to 12,000 samples. Choose Auto or set transparency to 0% and use Surface.",
    "viewer.hide_controls": "◀ Hide Controls", "viewer.show_controls": "▶ Show Controls",
    "viewer.mark_tool": "Mark Tool:", "viewer.choose_mark": "Choose Mark", "viewer.add": "Add",
    "viewer.delete": "Delete", "viewer.clear_tools": "Clear Tools", "viewer.pane_layout": "Pane Layout:",
    "viewer.sync_trace": "Sync Trace", "viewer.sync_x": "Sync X Range", "viewer.reset_layout": "Reset Layout",
    "interaction.pointer": "Pointer / Normal", "interaction.drag_share": "Drag-to-Share",
    "interaction.drag_target": "Drag Target:", "interaction.active_pane": "Active Pane",
    "interaction.all_panes": "All Panes", "interaction.drag_all": "Drag All Panes",
    "interaction.drag_active": "Drag Active Pane",
    "analysis.title": "YIG Mirror Analysis", "analysis.data_preview": "Data Preview",
    "analysis.fit_results": "Fit Results", "analysis.continuous_fit": "Continuous Fit",
    "analysis.phase_node": "Phase / Node", "analysis.grid_view": "Grid View",
    "analysis.focus_pane": "Focus Pane", "analysis.view_all": "View All",
    "analysis.reset_layout": "Reset Layout", "analysis.copy_this": "Copy This Pane",
    "analysis.copy_all": "Copy All Panes", "analysis.copy": "Copy", "analysis.save_this": "Save This Pane...",
    "analysis.save_all": "Save All Panes...", "analysis.source_data": "2D Source Data",
    "analysis.selected_trace": "Selected 1D Trace", "analysis.parameter_table": "Parameter Table",
    "analysis.fit_report": "Fit Report", "analysis.controls": "Analysis Controls",
    "analysis.data": "DATA", "analysis.preprocessing": "PREPROCESSING",
    "analysis.fit_model": "FIT MODEL", "analysis.fit_settings": "FIT SETTINGS",
    "analysis.single_fit": "SINGLE FIT", "analysis.output": "OUTPUT",
    "analysis.continuous_fit_settings": "CONTINUOUS FIT SETTINGS",
    "analysis.source_current": "Source: Current Viewer Data", "analysis.no_data": "No Data loaded",
    "analysis.full_range": "Full Range", "analysis.preview_fit_range": "Preview follows fit range",
    "analysis.s_parameter": "S Parameter", "analysis.sweep_axis": "Sweep Axis",
    "analysis.axis_scale": "Axis Scale", "analysis.slice": "Slice",
    "analysis.frequency_start": "Frequency Start", "analysis.frequency_stop": "Frequency Stop",
    "analysis.select_range_help": "Drag on the 1D trace to select a frequency range; click the 2D map to select a slice.",
    "analysis.hampel_filter": "Hampel outlier filter", "analysis.window_half_width": "Window Half-Width",
    "analysis.threshold": "Threshold", "analysis.dilation": "Dilation", "analysis.components": "Components",
    "analysis.manual_exclusion": "Manual Exclusion", "analysis.add_exclusion": "Drag on trace to add exclusion range",
    "analysis.clear_exclusions": "Clear Exclusions", "analysis.load_model": "Load Model .py...",
    "analysis.reload_model": "Reload Model", "analysis.model_builder": "Model Builder...",
    "analysis.no_model": "No model loaded", "analysis.model_function": "Model Function",
    "analysis.model_library": "Model Library...", "analysis.add_library": "Add to Library",
    "analysis.fit_weighting": "Resonance weighting: σ = |S| + ε", "analysis.method": "method",
    "analysis.loss": "loss", "analysis.maxfev": "maxfev", "analysis.fit_tolerance": "ftol / xtol",
    "analysis.auto_guess": "Auto Guess", "analysis.preview_initial": "Preview Initial Fit",
    "analysis.start_fit": "Start Fit", "analysis.fitted_initial": "Fitted → Initial",
    "analysis.copy_report": "Copy Fit Report", "analysis.save_settings": "Save Settings",
    "analysis.load_settings": "Load Settings", "analysis.export_result": "Export Result CSV",
    "analysis.browse": "Browse...", "analysis.open": "Open", "analysis.output_folder": "Folder",
    "analysis.auto_single_csv": "Save single-fit CSV and plot automatically",
    "analysis.auto_batch_csv": "Export Continuous Fit results automatically",
    "analysis.start_slice": "Start Slice", "analysis.end_slice": "End Slice",
    "analysis.stride": "Stride", "analysis.tracking_parameter_1": "Tracking Parameter 1",
    "analysis.tracking_parameter_2": "Tracking Parameter 2", "analysis.initial_guess_source": "Initial Guess Source",
    "analysis.r2_threshold": "R² Threshold", "analysis.stop_failure": "Stop on failure",
    "analysis.start_continuous": "Start Continuous Fit", "analysis.error_bars": "Error Bars",
    "analysis.successful_only": "Successful Only", "analysis.hide_fixed": "Hide Fixed Parameters",
    "analysis.show_trajectory": "Show Trajectory on 2D Map", "analysis.latest_live": "Show Latest Slice Live",
    "analysis.export_csv": "Export CSV", "analysis.load_csv": "Load CSV",
    "analysis.physical_mapping": "PHYSICAL MAPPING", "analysis.phase_parameter": "Phase Parameter φ",
    "analysis.resonance_frequency_parameter": "Resonance Frequency Parameter",
    "analysis.coupling_parameter": "Coupling Parameter κ_b", "analysis.phase_period": "Phase Period P",
    "analysis.phase_estimator": "PHASE LINE  φ = φ_ref + 2π·T·(f_m − f_ref)",
    "analysis.estimate_continuous": "Estimate from Continuous Fit",
    "analysis.dip_candidates": "Dip Candidate Frequencies", "analysis.candidate_threshold": "Candidate Threshold",
    "analysis.extract_dips": "Extract Dip Candidates", "analysis.estimate_candidates": "Estimate from Candidates",
    "analysis.show_physical_marks": "Show Physical Node/Antinode on Data Preview",
    "analysis.refresh": "Refresh", "analysis.export_locations": "Export Location Results CSV...",
    "analysis.coarse_detector": "COARSE DETECTOR", "analysis.global_linked_fit": "GLOBAL LINKED FIT",
    "debug.application_version": "Application Version",
    "debug.developer": "Developer", "debug.co_developer": "Co-developer",
    "debug.python_version": "Python Version", "debug.pyside_version": "PySide6 Version",
    "debug.qt_version": "Qt Version", "debug.operating_system": "Operating System",
    "debug.platform_architecture": "Platform / Architecture",
    "debug.renderer_backend": "Renderer Backend", "debug.graphics_device": "Graphics Device",
    "debug.three_d_status": "3D Availability / Status",
    "debug.mesh_dimensions": "Current Mesh Dimensions", "debug.approximate_fps": "Approximate FPS",
    "debug.approximate_frame_time": "Approximate Frame Time",
    "debug.copy_information": "Copy Debug Information", "debug.refresh": "Refresh",
    "debug.state.not_active": "Not active", "debug.state.not_queried": "Not queried",
    "debug.state.unavailable": "Unavailable", "debug.state.scene_active": "Scene active",
    "debug.state.context_available": "OpenGL context available",
    "debug.state.context_unavailable": "OpenGL context unavailable",
    "debug.state.undetermined": "Availability could not be determined",
    "debug.state.no_mesh": "No mesh", "debug.state.not_yet_available": "Not available yet",
    "tag.project": "Project", "tag.level": "Level", "tag.board_design": "Board Design",
    "tag.data_analysis": "Data Analysis", "tag.other": "Other", "tag.add_tag": "Add Tag...",
    "tag.category.project": "Project", "tag.category.level": "Level",
    "tag.category.board_design": "Board Design", "tag.category.data_analysis": "Data Analysis",
    "tag.category.other": "Other",
    "tag.rename_tag": "Rename Tag...", "tag.change_category": "Change Category...",
    "tag.manage": "Manage Tags", "tag.available": "Available Tags", "tag.new": "+ New Tag",
    "tag.invalid": "Tag name cannot be empty.", "tag.duplicate": "That Tag already exists.",
    "dialog.cancel": "Cancel", "dialog.close": "Close", "dialog.save": "Save",
    "dialog.confirm": "Confirm", "dialog.error": "Error", "dialog.warning": "Warning",
    "dialog.information": "Information", "dialog.yes": "Yes", "dialog.no": "No",
    "interfaces.measurement_unconfigured": "Measurement interface is not configured yet.",
    "interfaces.time_domain_unconfigured": "Time Domain interface is not configured yet.",
    "interfaces.launch_failed": "The interface could not be started.",
    "interfaces.paper_library_failed": "The Online Paper Library could not be opened in the default browser.",
}

ZH_TW = {
    "menu.file": "檔案(&F)", "menu.tags": "標籤(&T)", "menu.processing": "資料處理(&P)",
    "menu.interfaces": "介面",
    "menu.settings": "設定(&S)", "menu.view": "檢視(&V)", "menu.analysis": "分析(&A)",
    "action.open_database": "開啟資料庫...", "action.reload_database": "重新載入資料庫",
    "action.exit": "結束(&X)", "action.manage_tags": "管理標籤...",
    "action.retrieve_tags": "依標籤篩選...", "action.debackground": "背景扣除...",
    "action.settings": "設定...", "action.measurement": "量測",
    "action.time_domain": "時域", "action.online_paper_library": "線上論文庫",
    "action.open": "開啟...", "action.reload": "重新載入",
    "action.open_data_table": "資料表", "action.metadata": "中繼資料",
    "action.traces": "Trace 管理", "action.show": "顯示", "action.export": "匯出",
    "action.cancel": "取消", "action.save": "儲存", "action.delete": "刪除",
    "action.rename": "重新命名", "action.search": "搜尋", "action.add": "新增",
    "browser.no_database": "尚未開啟資料庫。請從「檔案 → 開啟資料庫」開始。",
    "browser.open_database": "開啟資料庫...", "browser.reload_database": "重新載入資料庫",
    "browser.star": "加入星號", "browser.unstar": "移除星號", "browser.tag": "標籤...",
    "browser.star_column": "星號", "browser.star_cell_starred": "已加星號 · 點擊移除星號",
    "browser.star_cell_unstarred": "未加星號 · 點擊加入星號",
    "browser.glass_thickness": "厚度", "browser.glass_frost": "霜化",
    "browser.glass_thickness_tip": "玻璃厚度：折射深度與邊緣高光",
    "browser.glass_frost_tip": "玻璃霜化：模糊與霧面感",
    "browser.glass_unavailable": "玻璃效果已關閉（安全復原模式或 LABLOGVIEWER_DISABLE_GLASS）",
    "viewer.restore_layout": "還原版面",
    "browser.retrieve_by_tags": "依標籤篩選...", "browser.back_to_folder": "返回資料夾",
    "browser.folders": "資料夾", "browser.tags_selected": "所選 Data 的標籤",
    "browser.data_folder": "資料夾中的 Data", "browser.edit_tags": "編輯標籤...",
    "browser.no_data_selected": "尚未選取 Data", "browser.no_tags": "沒有標籤",
    "browser.tags_none": "標籤：無", "browser.log_name": "Log 名稱",
    "browser.date_created": "建立日期", "browser.sweep_dimension": "Sweep 維度",
    "browser.source_folder": "來源資料夾", "browser.tags": "標籤",
    "browser.quick_preview": "快速預覽", "browser.comment": "備註",
    "browser.select_tags": "選取標籤", "browser.match": "符合方式", "browser.recent": "最近使用",
    "browser.clear_recent": "清除最近使用", "browser.retrieve": "篩選",
    "settings.general": "一般", "settings.appearance": "外觀",
    "settings.debug": "偵錯", "settings.about": "關於",
    "settings.language": "語言", "settings.title": "設定",
    "theme.light": "淺色", "theme.dark": "深色", "theme.system": "跟隨系統",
    "settings.advanced": "進階", "settings.scientific_plot_appearance": "科學圖外觀",
    "settings.export_plot_background": "匯出圖表背景",
    "settings.appearance_menu": "外觀...", "settings.theme": "主題",
    "settings.glass": "工具列玻璃",
    "settings.three_d": "3D", "settings.three_d_menu": "3D...",
    "three_d.open": "開啟 HDF5...",
    "net.address": "或輸入位址：",
    "net.address_placeholder": "Host 的 IP（例如 192.168.1.20 或 192.168.1.20:47811）",
    "net.address_tip": "自動搜尋找不到時使用（部分網路會擋搜尋）。",
    "net.firewall_notice": "Windows 接下來會詢問是否允許 LabLogViewer 接受連線。請勾選「私人網路」並按「允許」，否則其他電腦無法加入。",
    "settings.cloud_blocked": "此資料夾由 {service} 同步。歷史操作紀錄（星號、標籤、Mark、工作階段、分析紀錄）不允許放在雲端同步資料夾：同步可能把檔案移出本機或產生衝突副本，導致紀錄遺失。",
    "settings.cloud_consent": "我了解：若歷史操作資料遺失由我自行負責，開發者無權也無法回溯。",
    "settings.cloud_move_anyway": "仍要搬移",
    "settings.cloud_current": "警告：資料夾目前由 {service} 同步，建議搬到本機資料夾以保護歷史紀錄。",
    "settings.personal": "個人化",
    "personal.colors": "配色",
    "personal.icons": "圖示",
    "personal.item": "項目",
    "personal.code": "顏色編號",
    "personal.reset_one": "恢復此顏色",
    "personal.reset_group": "恢復此組",
    "personal.reset_all": "恢復全部配色",
    "personal.group_app_light": "淺色主題",
    "personal.group_app_dark": "深色主題",
    "personal.group_plot_white": "科學圖 — 白底",
    "personal.group_plot_dark": "科學圖 — 深底",
    "personal.group_pens": "標註畫筆",
    "personal.low_contrast": "{group}：{fg} 放在 {bg} 上不易閱讀（對比 {ratio:.1f}，建議 3.0 以上）。",
    "personal.icons_note": "可用自己的 SVG 檔替換任何圖示（僅限純 SVG：不可含程式、連結或內嵌圖片；最大 256 KB）。會另存一份你的檔案，原始圖示保留。",
    "personal.locked": "個人配色需累積 10 筆數據操作經驗後解鎖（在不同的測量檔上放 Mark、切換轉換、縮放、擬合⋯⋯），還需 {remaining} 筆。圖示現在就可以更換。",
    "personal.unlocked": "個人配色已解鎖。",
    "personal.unlocked_license": "個人配色已由授權檔解鎖，有效至 {date}。",
    "license.open": "授權⋯", "license.title": "授權",
    "license.intro": "開發者提供的授權檔（.llvkey）可在一台電腦上解鎖功能。申請時請把下方機器碼傳給開發者。授權有期限（通常兩個月），到期可再申請。",
    "license.machine_code": "機器碼：", "license.copy": "複製",
    "license.holder": "持有人", "license.features": "功能", "license.expires": "有效至", "license.status": "狀態",
    "license.install": "安裝授權檔⋯", "license.remove": "移除",
    "license.valid_days": "有效（剩 {days} 天）", "license.installed": "授權檔已安裝。",
    "license.feature_personal_colors": "個人配色", "license.feature_relink": "重新連結搬移的資料",
    "license.feature_migrate": "資料轉移", "migrate.open": "資料轉移⋯",
    "license.error_format": "這不是 LabLogViewer 的授權檔。",
    "license.error_signature": "授權檔簽章無效（檔案被修改過，或不是開發者發出的）。",
    "license.error_machine": "這個授權檔是給另一台電腦的。",
    "license.error_expired": "這個授權檔已過期，請向開發者重新申請。",
    "license.error_no_key": "此版本的 LabLogViewer 無法驗證授權（未安裝開發者公鑰）。",
    "license.program": "這個程式：LabLogViewer {version} — {folder}",
    "settings.app_icon": "App 圖示", "settings.app_icon_n": "圖示 {n}",
    "settings.auto_refresh": "自動刷新（新的與變動的量測）",
    "settings.auto_refresh_off": "關閉", "settings.auto_refresh_n": "每 {n} 秒",
    "settings.auto_refresh_tip": "只比對檔案大小與時間（很省資源，放在共用儲存空間也適用）；只有新增或變動的檔案才會重新讀取。開著的 Viewer 會跟著正在進行的量測更新。",
    "browser.auto_refresh_done": "自動刷新：新增 {added}、更新 {changed}、移除 {removed}",
    "action.new_folder": "新增資料夾⋯", "browser.new_folder": "新增資料夾⋯",
    "browser.new_folder_title": "新增資料夾", "browser.new_folder_prompt": "在 {parent} 裡新增的資料夾名稱：",
    "browser.new_folder_empty": "請輸入資料夾名稱。",
    "browser.new_folder_bad": "資料夾名稱不能含有 / \\ : * ? \" < > |，不能以句點開頭，也不能以空白或句點結尾。",
    "browser.new_folder_exists": "這裡已經有「{name}」。",
    "browser.new_folder_failed": "無法建立資料夾：{reason}",
    "browser.new_folder_done": "已建立資料夾：{name}",
    "whatsnew.title": "LabLogViewer {version} 新功能", "whatsnew.open": "新功能⋯",
    "whatsnew.heading": "LabLogViewer {version}", "whatsnew.updated": "已從 {old} 更新到 {new}",
    "whatsnew.earlier": "較早的版本", "whatsnew.none": "這個版本沒有說明。",
    "whatsnew.newer_title": "請更新 LabLogViewer",
    "whatsnew.newer_data": "你的紀錄是由較新版本的 LabLogViewer 建立的。這個舊版本不會更動它們，但有些新紀錄可能無法顯示。請安裝最新版本。",
    "whatsnew.upgrade_failed_title": "紀錄沒有升級",
    "whatsnew.upgrade_failed": "把紀錄調整成這個版本的格式時失敗，已還原成原本的樣子（備份在資料夾的 update_backups 裡）。原因：{reason}",
    "license.key_ok": "開發者公鑰：已安裝（{key}）",
    "license.key_missing": "開發者公鑰：未安裝──這個程式無法驗證授權",
    "license.key_where": "公鑰必須裝在這個資料夾：\n{folder}\n（授權產生器：選這個 LabLogViewer 資料夾，再產生一次即可）。",
    "license.error_clock": "這台電腦的日期早於授權檔的發出日期，請檢查時鐘。",
    "relink.open": "重新連結搬移的資料⋯", "relink.title": "重新連結搬移的資料",
    "relink.intro": "歷史紀錄（星號、標籤、註解、Mark、視圖、3D 視角、YIG 工作階段）是跟著檔案原本的路徑存的。若檔案被搬走，請選擇它們現在所在的資料夾後按「尋找檔案」（依內容比對，改過檔名也找得到）；若只是整個資料夾或 NAS 掛載名稱變了，選好舊資料夾後按「依路徑對應」（很快）。紀錄會移到新路徑。修改前會先備份紀錄檔，且可以復原。測量檔只會被讀取。",
    "relink.missing": "有 {count} 個舊路徑有紀錄但檔案已不在（其中 {fingerprinted} 個有內容指紋）。",
    "relink.new_folder": "搬移後所在資料夾：", "relink.browse": "瀏覽⋯", "relink.search": "尋找檔案",
    "relink.old_path": "舊路徑", "relink.new_path": "找到的位置", "relink.match": "比對", "relink.records": "紀錄",
    "relink.conf_exact": "內容相同", "relink.conf_guess": "檔名與大小相同（請確認）", "relink.not_found": "找不到",
    "relink.guess_note": "「內容相同」的列已勾選。「檔名與大小相同」的列沒有指紋可比對，確定是同一個檔案再勾選。",
    "relink.apply": "重新連結已勾選的列", "relink.undo": "復原上一次重新連結",
    "relink.close_viewers": "請先關閉所有 Viewer 視窗。",
    "relink.confirm": "要把 {count} 個檔案的紀錄移到新路徑嗎？修改前會先備份紀錄檔。",
    "relink.done": "已重新連結 {count} 個檔案。備份：{backup}", "relink.conflicts": "以下保留新路徑原有的紀錄（依你的選擇）：",
    "relink.undo_confirm": "要把紀錄還原到上一次重新連結之前嗎？之後對這些紀錄所做的修改會遺失。",
    "relink.undone": "已復原上一次重新連結。",
    "save.exists_title": "已有同名檔案", "save.exists_text": "「{name}」已經存在於\n{folder}",
    "save.exists_info": "「覆蓋」會取代它；「兩者都保留」會把新的存成「{new_name}」。",
    "save.exists_no_replace": "這裡不能取代它；「兩者都保留」會改用「{new_name}」。",
    "save.overwrite": "覆蓋", "save.keep_both": "兩者都保留", "save.choose_another": "另選⋯",
    "save.cancel": "取消",
    "relink.old_folder": "舊資料夾（快速，依路徑）：", "relink.by_path": "依路徑對應",
    "relink.by_path_tip": "檔案在資料夾裡的位置沒變，只是整個資料夾搬走，或 NAS 掛載名稱變了時使用：把每個舊路徑前段的「舊資料夾」換成上方的資料夾。只檢查檔名與大小，不讀內容，在 NAS 上也很快。",
    "relink.conf_path": "位置相同、大小相同",
    "relink.conflict_question": "有 {count} 筆紀錄在舊路徑和新路徑都有，都是你做的，而且內容不同（見詳細資訊）。新路徑上由程式自動產生的紀錄（自動標籤、第一次開啟的視圖）會直接由舊紀錄取代，不會詢問。\n\n這 {count} 筆要保留哪一份？",
    "relink.use_old": "用舊紀錄覆蓋", "relink.keep_new": "保留目前的紀錄",
    "settings.tag_root": "最大資料夾（標籤搜尋）",
    "settings.tag_root_note": "集中存放所有量測資料的超大資料夾。「依標籤篩選」可以改為搜尋整個最大資料夾，而不只目前的資料庫。搜尋的是 LabLogViewer 的標籤紀錄（上百萬筆也很快），因此檔案所在的資料庫要被開啟過才找得到。自動標籤只會加在開啟的資料庫往下 4 層資料夾以內的檔案。",
    "settings.tag_root_browse": "瀏覽⋯", "settings.tag_root_clear": "清除", "settings.tag_root_none": "未設定",
    "fig.menu": "科學示意圖建構器⋯", "fig.title": "科學示意圖建構器",
    "fig.crashed": "示意圖建構器意外關閉（{reason}）。LabLogViewer 其他部分不受影響，可從「處理」再次開啟。",
    "fig.open_dxf": "開啟 DXF⋯", "fig.open_project": "開啟示意圖⋯", "fig.save_project": "儲存示意圖⋯",
    "fig.add_yig": "加入 YIG", "fig.add_coil": "加入線圈", "fig.add_wave": "加入正弦波", "fig.delete": "刪除",
    "fig.undo": "復原", "fig.redo": "重做", "fig.export_pptx": "輸出 PowerPoint⋯", "fig.export_image": "輸出圖片⋯",
    "fig.layers": "圖層", "fig.selection": "選取項目", "fig.view": "視角",
    "fig.empty": "請開啟 DXF 圖檔（AutoCAD 2013）。\n圖層：b、g、h（微帶線）或 db、ub、g、h、v（共面波導）。",
    "fig.col_show": "顯示", "fig.col_layer": "圖層", "fig.col_color": "顏色", "fig.col_thickness": "厚度",
    "fig.col_place": "位置", "fig.layer_up": "上移", "fig.layer_down": "下移",
    "fig.place_stack": "疊在下層上", "fig.place_same": "與下層同高", "fig.place_through": "貫穿全部",
    "fig.mode_ms": "模式：微帶線（MS）", "fig.mode_cpw": "模式：共面波導（CPW）",
    "fig.elevation": "俯仰角", "fig.azimuth": "旋轉", "fig.background": "背景",
    "fig.no_selection": "點選 YIG、線圈或正弦波來編輯。\n拖曳空白處可轉動視角。",
    "fig.yig_radius": "半徑（mm）", "fig.yig_lift": "離表面高度（mm）", "fig.yig_spins": "自旋箭頭數",
    "fig.yig_color": "球體顏色", "fig.yig_spin_color": "自旋顏色",
    "fig.coil_radius": "半徑（mm）", "fig.coil_wire": "線徑（mm）", "fig.coil_turns": "圈數",
    "fig.coil_pitch": "圈距（mm）", "fig.coil_gap": "與板底距離（mm）", "fig.coil_color": "顏色",
    "fig.coil_arrow": "磁場箭頭", "fig.coil_arrow_color": "箭頭顏色",
    "fig.wave_cycles": "週期數", "fig.wave_phase": "相位（度）", "fig.wave_width": "線寬（pt）",
    "fig.wave_dashed": "虛線", "fig.wave_color": "顏色",
    "personal.follow_theme": "跟隨主題換色（淺色 / 深色時重新上色）",
    "personal.replace_icon": "以 SVG 替換...",
    "personal.restore_icon": "恢復預設",
    "personal.restore_all_icons": "恢復全部圖示",
    "personal.svg_rejected": "這個 SVG 無法使用：{reason}",
    "personal.field_window": "視窗底色",
    "personal.field_panel": "面板",
    "personal.field_alternate": "交錯列 / 滑過",
    "personal.field_text": "文字",
    "personal.field_secondary": "次要文字",
    "personal.field_border": "邊框",
    "personal.field_accent": "強調色",
    "personal.field_selected": "選取",
    "personal.field_plot_background": "繪圖背景",
    "personal.field_plot_panel": "繪圖面板",
    "personal.field_control": "按鈕 / 控制項",
    "personal.field_input": "輸入框",
    "personal.field_background": "背景",
    "personal.field_red": "紅筆",
    "personal.field_blue": "藍筆",
    "personal.field_yellow": "黃筆",
    "personal.field_green": "綠筆",
    "personal.field_laser": "雷射筆",
    "interaction.zoom": "局部放大",
    "interaction.zoom_tip": "局部放大：按住左鍵拖出矩形；右鍵或 Esc 退回上一層。",
    "help.title": "LabLogViewer 說明",
    "help.search": "搜尋說明",
    "help.export_ai": "匯出給 AI...",
    "help.include_state": "附上目前狀態（版本、系統、開啟的視窗；不含資料、路徑與使用者名稱）",
    "help.save_file": "儲存檔案...",
    "help.copy_text": "複製文字",
    "net.title": "網路工作區",
    "net.host": "Host（主持）",
    "net.client": "Client（加入）",
    "net.rename": "重新命名...",
    "net.this_computer": "本機名稱：{name}",
    "net.name_title": "為這台電腦命名",
    "net.name_prompt": "在網路工作區中顯示給其他人的名稱（任何語言皆可）：",
    "net.session": "工作區 / Session",
    "net.session_placeholder": "例如：週二組會",
    "net.status": "狀態",
    "net.join_code": "加入碼",
    "net.sharing": "正在分享",
    "net.clients": "已連線的 Client",
    "net.send_copy": "送出永久副本...",
    "net.send_copy_tip": "只有 Host 能把目前量測的永久副本給 Client。",
    "net.send_copy_confirm": "要把目前的 HDF5 檔永久副本送給 {name} 嗎？對方電腦會保存這個檔案。",
    "net.start_hosting": "開始主持",
    "net.stop_hosting": "停止主持",
    "net.cannot_host": "無法開始主持：{reason}",
    "net.hosting": "主持中 · {count} / 5 位 Client",
    "net.not_hosting": "未主持",
    "net.open_viewer": "在 Viewer 開啟量測即可分享。",
    "net.search_placeholder": "搜尋 Host 名稱或 Session 名稱",
    "net.search": "搜尋",
    "net.searching": "正在搜尋此網域...",
    "net.found": "找到 {count} 個 Host。",
    "net.none_found": "找不到 Host。請再搜尋一次，或確認兩台電腦在同一個網域。",
    "net.host_row": "{host} — {session}（{clients}/{max}）",
    "net.host_info": "Host / 工作區",
    "net.shared_folders": "共用資料夾...",
    "net.shared_folders_tip": "若本機也讀得到同一個檔案（例如共用儲存），會直接使用而不下載。",
    "net.shared_folders_list": "共用資料夾：{folders}",
    "net.none": "無",
    "net.connect": "連線",
    "net.disconnect": "中斷連線",
    "net.pick_host": "請先選擇一個 Host。",
    "net.offline": "離線",
    "net.leave": "離開",
    "net.following": "正在跟隨 {host} · {session}（唯讀）",
    "net.source_local": "資料：本機",
    "net.source_host": "資料：來自 Host（僅記憶體）",
    "net.mirror_title": "{name} — 跟隨 {host}（唯讀）",
    "net.yig_mirror_title": "YIG Analysis — 跟隨 {host} — {title}",
    "net.receiving_structure": "正在接收量測結構...",
    "net.receiving_data": "正在接收資料",
    "net.transfer_failed": "傳輸失敗：{reason}",
    "net.host_in_3d": "Host 正在看 3D 視圖，3D 不提供網路同步。",
    "net.copy_failed": "Host 傳來的副本校驗碼不符，已丟棄。",
    "net.copy_received": "Host 送來一份永久副本，已儲存到：\n{path}",
    "net.state_connecting": "連線中",
    "net.state_connected": "已連線",
    "net.state_reconnecting": "重新連線中",
    "net.state_disconnected": "已中斷",
    "net.level_excellent": "優",
    "net.level_good": "良",
    "net.level_fair": "尚可",
    "net.level_unusable": "太差",
    "net.level_unknown": "量測中",
    "net.reason_wrong_code": "加入碼錯誤",
    "net.reason_host_full": "Host 已有 5 位 Client",
    "net.reason_not_same_subnet": "兩台電腦不在同一個網域",
    "net.reason_poor_quality": "網路品質低於門檻（延遲 200 ms、1 MB/s）",
    "net.reason_host_unavailable": "找不到 Host",
    "net.reason_host_closed": "Host 已停止主持",
    "net.reason_timeout": "逾時",
    "net.reason_left": "你已離開",
    "net.reason_protocol_mismatch": "雙方 LabLogViewer 網路版本不同",
    "net.reason_too_many_attempts": "加入碼錯誤太多次，請等一分鐘",
    "three_d.crash_title": "3D 視窗已關閉",
    "three_d.crash_text": "3D Surface 視窗意外停止（它在獨立程序中執行，常見原因是顯示卡驅動）。LabLogViewer 其他部分不受影響，資料沒有遺失。",
    "three_d.reopen": "重新開啟 3D",
    "trust.title": "要信任這個模型檔嗎？",
    "trust.intro": "{name} 是 Python 程式碼，載入時會以你的權限執行。只信任你自己寫的、或來自可信任對象的模型檔。請先檢查下方程式碼。只會詢問一次；檔案內容改變後會再詢問。",
    "trust.warnings": "請留意：", "trust.trust": "信任並載入",
    "settings.data_folder": "資料夾位置", "settings.data_folder_current": "位置",
    "settings.data_folder_browse": "變更位置...", "settings.data_folder_open": "顯示資料夾",
    "settings.data_folder_default": "使用預設",
    "settings.data_folder_choose": "選擇 LabLogViewerData 資料夾的存放位置",
    "settings.data_folder_tip": "星號、標籤、註解、標記、轉換、工作階段與分析紀錄。HDF5 檔中的量測數值永遠不會被修改（註解可能會寫入 Labber 自己的註解欄位）。",
    "settings.data_folder_pending": "下次啟動時將移至",
    "settings.data_folder_occupied": "{path} 已經有 LabLogViewer 資料。\n\n要改用該資料夾裡的資料嗎？目前的資料夾不會變動。",
    "settings.data_folder_restart": "資料夾會在下次啟動 LabLogViewer 時變更（屆時一併搬移所有紀錄）。\n\n現在要關閉 LabLogViewer 嗎？",
    "settings.three_d_profile": "3D 效能", "settings.profile_balanced": "平衡",
    "settings.profile_quality": "高畫質", "settings.profile_economy": "省資源",
    "settings.three_d_profile_tip": "3D 曲面的顯示頂點上限；原始資料不會被更改。",
    "settings.white_background": "白色背景", "settings.dark_background": "深色背景",
    "language.english": "English", "language.traditional_chinese": "中文（繁體）",
    "language.english_name": "英文", "language.chinese_name": "繁體中文",
    "viewer.plot_mode": "繪圖模式：", "viewer.one_d": "1D 繪圖", "viewer.two_d": "2D 熱圖",
    "viewer.nd": "3D 曲面", "viewer.maximize": "最大化繪圖",
    "viewer.nd_visualization": "多維顯示方式：", "viewer.nd_heatmap": "2D 熱圖",
    "viewer.surface_3d": "3D 曲面", "viewer.reset_view": "重設視角",
    "viewer.view_all": "檢視全部",
    "viewer.surface_sampling": "顯示取樣：{source_rows} × {source_columns} → {rows} × {columns} 個頂點。科學資料未變更。",
    "viewer.surface_gaps": "{count} 個非有限 Z 值以缺口顯示。",
    "viewer.surface_error": "無法顯示 3D Surface：{reason}",
    "viewer.axis_x": "X", "viewer.axis_y": "Y", "viewer.height_z": "高度（Z）",
    "viewer.transform": "轉換", "viewer.surface": "表面",
    "viewer.color": "色彩", "viewer.rendering": "渲染方式",
    "viewer.policy_auto": "自動", "viewer.policy_full": "完整解析度",
    "viewer.policy_adaptive": "自適應 LOD", "viewer.policy_performance": "效能優先",
    "viewer.z_scale": "Z 軸比例", "viewer.z_scale_range": "僅調整視覺垂直比例（0.1x 至 10x）",
    "viewer.auto": "自動", "viewer.reset_z_scale": "重設 Z 軸比例",
    "viewer.projection": "投影方式", "viewer.perspective": "透視",
    "viewer.orthographic": "正交", "viewer.color_source": "顏色來源",
    "viewer.same_as_height": "與高度相同", "viewer.colormap": "色彩映射",
    "viewer.minimum": "最小值", "viewer.maximum": "最大值",
    "viewer.auto_range": "自動範圍", "viewer.camera": "相機",
    "viewer.camera_top": "頂視", "viewer.camera_front": "前視",
    "viewer.camera_side": "側視", "viewer.camera_isometric": "等角視圖",
    "viewer.geometry_type": "幾何類型",
    "viewer.opacity": "不透明度",
    "viewer.transparency": "透明度",
    "viewer.surface_a_opacity": "Surface A 不透明度",
    "viewer.surface_b_mapping": "Surface B 映射",
    "viewer.surface_b_opacity": "Surface B 不透明度",
    "viewer.plane_value": "平面數值",
    "viewer.point_color": "點顏色",
    "viewer.point_size_3d": "點大小",
    "viewer.point_x": "點 X",
    "viewer.point_y": "點 Y",
    "viewer.point_z": "點 Z",
    "viewer.reference_plane": "參考平面",
    "viewer.unwrap_along": "Unwrap 方向",
    "viewer.along_x": "沿 X",
    "viewer.along_y": "沿 Y",
    "viewer.bottom_projection": "底部投影",
    "viewer.top_colorbar": "頂部互動色條",
    "viewer.reference_off": "關閉",
    "viewer.reference_custom_mode": "自訂",
    "viewer.zero_plane": "零平面",
    "viewer.surface_3d_menu": "3D Surface…",
    "annotation.toggle": "標註",
    "annotation.pen": "畫筆",
    "annotation.laser": "雷射筆",
    "annotation.clear": "清屏",
    "annotation.width": "粗細",
    "annotation.trail": "拖尾",
    "annotation.red": "紅",
    "annotation.blue": "藍",
    "annotation.yellow": "黃",
    "annotation.green": "綠",
    "viewer.copy_3d": "複製 3D 圖",
    "viewer.save_3d": "儲存 3D 圖…",
    "viewer.copied_3d": "已複製 3D 圖。",
    "viewer.export_style_publication": "匯出：論文樣式",
    "viewer.export_style_screen": "匯出：螢幕畫面",
    "settings.three_d_export_style": "3D 匯出樣式",
    "settings.export_style_publication": "論文樣式（期刊圖）",
    "settings.export_style_screen": "螢幕畫面",
    "settings.three_d_export_style_tip": "論文樣式輸出期刊風格圖（PNG/PDF/SVG）；螢幕畫面則擷取互動視圖。",
    "viewer.advanced": "進階", "viewer.slice_dimensions": "切片維度",
    "viewer.no_second_dimension": "沒有第二個維度",
    "viewer.surface_select_data": "請選擇 Data 以建立 Surface。",
    "viewer.surface_needs_xy": "請選擇不同的 X 與 Y 維度以建立 3D Surface。",
    "viewer.surface_loading": "正在準備科學 Surface…",
    "viewer.surface_single_pane": "3D Surface 目前僅支援單一 Viewer Pane。",
    "viewer.surface_large_warning": "大型網格：互動顯示使用簡化網格；仍可手動選擇完整解析度。",
    "viewer.surface_grid_status": "網格 {source_rows} × {source_columns}；顯示 {vertices} 個頂點；{policy}。",
    "viewer.surface_performance": "{fps:.1f} FPS（每影格 {frame_ms:.1f} ms）",
    "viewer.reference_outside": "參考平面 {value} 超出高度範圍 {low} … {high}。",
    "viewer.reference_minimum": "最小值平面：{value}", "viewer.reference_zero": "零平面：{value}",
    "viewer.reference_custom": "參考平面：{value}",
    "viewer.waterfall_traces": "{count} 條軌跡色帶",
    "viewer.surface_pick_hint": "左鍵拖曳：旋轉  ·  中鍵拖曳：平移  ·  滾輪：縮放  ·  左鍵點選：讀取科學數值",
    "viewer.surface_performance_details": "來源 {source_rows} × {source_columns}；顯示 {render_rows} × {render_columns}（{vertices} 個頂點）；{policy}。",
    "viewer.transparent_status": "透明曲面 · 顯示 {vertices:,} 點 / {source:,} 個來源點",
    "viewer.transparent_full_limit": "透明模式的完整解析度上限為 12,000 點。請選擇 Auto，或改用 Surface 顯示大型完整網格。",
    "viewer.hide_controls": "◀ 隱藏控制面板", "viewer.show_controls": "▶ 顯示控制面板",
    "viewer.mark_tool": "標記工具：", "viewer.choose_mark": "選擇標記", "viewer.add": "新增",
    "viewer.delete": "刪除", "viewer.clear_tools": "清除工具", "viewer.pane_layout": "Pane 配置：",
    "viewer.sync_trace": "同步 Trace", "viewer.sync_x": "同步 X 範圍", "viewer.reset_layout": "重設版面",
    "interaction.pointer": "指標 / 一般操作", "interaction.drag_share": "拖曳分享",
    "interaction.drag_target": "拖曳範圍：", "interaction.active_pane": "作用中 Pane",
    "interaction.all_panes": "所有 Panes", "interaction.drag_all": "拖曳所有 Panes",
    "interaction.drag_active": "拖曳作用中 Pane",
    "analysis.title": "YIG 鏡像分析", "analysis.data_preview": "資料預覽",
    "analysis.fit_results": "擬合結果", "analysis.continuous_fit": "連續擬合",
    "analysis.phase_node": "相位／Node", "analysis.grid_view": "格狀檢視",
    "analysis.focus_pane": "放大 Pane", "analysis.view_all": "檢視全部",
    "analysis.reset_layout": "重設版面", "analysis.copy_this": "複製此 Pane",
    "analysis.copy_all": "複製所有 Panes", "analysis.copy": "複製", "analysis.save_this": "儲存此 Pane...",
    "analysis.save_all": "儲存所有 Panes...", "analysis.source_data": "2D 原始資料",
    "analysis.selected_trace": "選取的 1D Trace", "analysis.parameter_table": "參數表",
    "analysis.fit_report": "擬合報告", "analysis.controls": "分析控制項",
    "analysis.data": "資料", "analysis.preprocessing": "前處理",
    "analysis.fit_model": "擬合模型", "analysis.fit_settings": "擬合設定",
    "analysis.single_fit": "單次擬合", "analysis.output": "輸出",
    "analysis.continuous_fit_settings": "連續擬合設定",
    "analysis.source_current": "來源：目前 Viewer Data", "analysis.no_data": "尚未載入 Data",
    "analysis.full_range": "完整範圍", "analysis.preview_fit_range": "預覽跟隨擬合範圍",
    "analysis.s_parameter": "S 參數", "analysis.sweep_axis": "Sweep 軸",
    "analysis.axis_scale": "軸縮放", "analysis.slice": "切片",
    "analysis.frequency_start": "起始頻率", "analysis.frequency_stop": "結束頻率",
    "analysis.select_range_help": "在 1D Trace 上拖曳選取頻率範圍；點擊 2D Map 選取切片。",
    "analysis.hampel_filter": "Hampel 離群值篩選", "analysis.window_half_width": "視窗半寬",
    "analysis.threshold": "閾值", "analysis.dilation": "擴張點數", "analysis.components": "分量",
    "analysis.manual_exclusion": "手動排除", "analysis.add_exclusion": "在 Trace 上拖曳以新增排除範圍",
    "analysis.clear_exclusions": "清除排除範圍", "analysis.load_model": "載入模型 .py...",
    "analysis.reload_model": "重新載入模型", "analysis.model_builder": "模型建立器...",
    "analysis.no_model": "尚未載入模型", "analysis.model_function": "模型函式",
    "analysis.model_library": "模型庫...", "analysis.add_library": "加入模型庫",
    "analysis.fit_weighting": "共振加權：σ = |S| + ε", "analysis.method": "方法",
    "analysis.loss": "損失函數", "analysis.maxfev": "最大函式評估次數", "analysis.fit_tolerance": "ftol / xtol",
    "analysis.auto_guess": "自動估計初值", "analysis.preview_initial": "預覽初始擬合",
    "analysis.start_fit": "開始擬合", "analysis.fitted_initial": "擬合值 → 初值",
    "analysis.copy_report": "複製擬合報告", "analysis.save_settings": "儲存設定",
    "analysis.load_settings": "載入設定", "analysis.export_result": "匯出結果 CSV",
    "analysis.browse": "瀏覽...", "analysis.open": "開啟", "analysis.output_folder": "資料夾",
    "analysis.auto_single_csv": "自動儲存單次擬合 CSV 與圖表",
    "analysis.auto_batch_csv": "自動匯出連續擬合結果",
    "analysis.start_slice": "起始切片", "analysis.end_slice": "結束切片",
    "analysis.stride": "步進", "analysis.tracking_parameter_1": "追蹤參數 1",
    "analysis.tracking_parameter_2": "追蹤參數 2", "analysis.initial_guess_source": "初值來源",
    "analysis.r2_threshold": "R² 閾值", "analysis.stop_failure": "失敗時停止",
    "analysis.start_continuous": "開始連續擬合", "analysis.error_bars": "誤差棒",
    "analysis.successful_only": "僅顯示成功項目", "analysis.hide_fixed": "隱藏固定參數",
    "analysis.show_trajectory": "在 2D Map 顯示軌跡", "analysis.latest_live": "即時顯示最新切片",
    "analysis.export_csv": "匯出 CSV", "analysis.load_csv": "載入 CSV",
    "analysis.physical_mapping": "物理對應", "analysis.phase_parameter": "相位參數 φ",
    "analysis.resonance_frequency_parameter": "共振頻率參數",
    "analysis.coupling_parameter": "耦合參數 κ_b", "analysis.phase_period": "Phase 週期 P",
    "analysis.phase_estimator": "相位線  φ = φ_ref + 2π·T·(f_m − f_ref)",
    "analysis.estimate_continuous": "由 Continuous Fit 估計",
    "analysis.dip_candidates": "Dip 候選頻率", "analysis.candidate_threshold": "候選閾值",
    "analysis.extract_dips": "擷取 Dip 候選", "analysis.estimate_candidates": "由候選值估計",
    "analysis.show_physical_marks": "在資料預覽顯示 Physical Node/Antinode",
    "analysis.refresh": "更新", "analysis.export_locations": "匯出位置結果 CSV...",
    "analysis.coarse_detector": "粗略偵測器", "analysis.global_linked_fit": "Global Linked Fit",
    "debug.application_version": "應用程式版本",
    "debug.developer": "開發者", "debug.co_developer": "共同開發者",
    "debug.python_version": "Python 版本", "debug.pyside_version": "PySide6 版本",
    "debug.qt_version": "Qt 版本", "debug.operating_system": "作業系統",
    "debug.platform_architecture": "平台／架構",
    "debug.renderer_backend": "繪圖後端", "debug.graphics_device": "圖形裝置",
    "debug.three_d_status": "3D 可用性／狀態",
    "debug.mesh_dimensions": "目前網格尺寸", "debug.approximate_fps": "約略 FPS",
    "debug.approximate_frame_time": "約略影格時間",
    "debug.copy_information": "複製偵錯資訊", "debug.refresh": "重新整理",
    "debug.state.not_active": "未啟用", "debug.state.not_queried": "尚未查詢",
    "debug.state.unavailable": "無法使用", "debug.state.scene_active": "場景作用中",
    "debug.state.context_available": "OpenGL context 可用",
    "debug.state.context_unavailable": "OpenGL context 無法使用",
    "debug.state.undetermined": "無法判定可用性",
    "debug.state.no_mesh": "沒有網格", "debug.state.not_yet_available": "目前無法取得",
    "tag.project": "專案", "tag.level": "等級", "tag.board_design": "電路板設計",
    "tag.data_analysis": "資料分析", "tag.other": "其他", "tag.add_tag": "新增標籤...",
    "tag.category.project": "專案", "tag.category.level": "等級",
    "tag.category.board_design": "電路板設計", "tag.category.data_analysis": "資料分析",
    "tag.category.other": "其他",
    "tag.rename_tag": "重新命名標籤...", "tag.change_category": "變更分類...",
    "tag.manage": "管理標籤", "tag.available": "可用標籤", "tag.new": "+ 新增標籤",
    "tag.invalid": "標籤名稱不可為空。", "tag.duplicate": "此標籤已存在。",
    "dialog.cancel": "取消", "dialog.close": "關閉", "dialog.save": "儲存",
    "dialog.confirm": "確認", "dialog.error": "錯誤", "dialog.warning": "警告",
    "dialog.information": "資訊", "dialog.yes": "是", "dialog.no": "否",
    "interfaces.measurement_unconfigured": "量測介面尚未設定。",
    "interfaces.time_domain_unconfigured": "Time Domain 介面尚未設定。",
    "interfaces.launch_failed": "介面無法啟動。",
    "interfaces.paper_library_failed": "無法使用預設瀏覽器開啟線上論文庫。",
}

CATALOGS = {"en": EN, "zh_TW": ZH_TW}
