"""Traditional Chinese for interface text written directly in English in the code.

UI:        exact English text -> Chinese.
PATTERNS:  English with {} placeholders -> Chinese with {0}, {1} ... (values are kept).
Scientific terms (S21, Hz, Magnitude ...) stay as they are (terminology.py).
Drop-down lists are translated only where they are drawn, so code that reads
the selected text still gets the English value.
"""

UI = {
    # -- menus and actions ---------------------------------------------------------------------
    "&Data Table": "資料表(&D)", "&Metadata": "中繼資料(&M)", "Data Table": "資料表", "Metadata": "中繼資料",
    "&Processing": "處理(&P)", "&File": "檔案(&F)", "&Tags": "標籤(&T)", "&Settings": "設定(&S)",
    "&View": "檢視(&V)", "&Analysis": "分析(&A)", "Interfaces": "介面", "Measurement": "量測", "Time Domain": "時域",
    "Online Paper Library": "線上論文庫", "Network Workspace": "網路工作區", "Help": "說明",
    "Copy Active Pane": "複製作用中窗格", "Copy Plot": "複製圖表", "Copy Report": "複製報告",
    "Save Active Pane As...": "另存作用中窗格⋯", "Save All Panes As...": "另存所有窗格⋯",
    "Save This Pane As...": "另存此窗格⋯", "Save Plot As...": "另存圖表⋯", "Save Plot...": "儲存圖表⋯",
    "Save Plot": "儲存圖表", "Save Analysis Plot": "儲存分析圖", "Save...": "儲存⋯", "Save .py...": "儲存 .py⋯",
    "Export Animation": "匯出動畫", "Export Animation...": "匯出動畫⋯", "Export Data": "匯出資料",
    "Export Data...": "匯出資料⋯", "Export Global Fit CSV": "匯出全域擬合 CSV", "Rename File...": "重新命名檔案⋯",
    "Manage Tags...": "管理標籤⋯", "Manage View Presets": "管理視圖預設", "Manage View Presets...": "管理視圖預設⋯",
    "Save View Preset": "儲存視圖預設", "Save View Preset...": "儲存視圖預設⋯", "Save Axis Preset": "儲存座標軸預設",
    "Save Axis Preset...": "儲存座標軸預設⋯", "YIG Mirror Analysis...": "YIG 鏡像分析⋯", "Open in Viewer": "在 Viewer 開啟",
    "Retrieve by Tags": "依標籤篩選", "Channel Browser": "通道瀏覽器", "Open Library Folder": "開啟模型庫資料夾",
    "Open Existing Builder File...": "開啟既有的建構器檔案⋯", "Open in Model Builder": "在模型建構器中開啟",
    "Edit in Library...": "在模型庫中編輯⋯", "Add from File...": "從檔案加入⋯", "Add Current Model": "加入目前模型",
    "Add to Model Library": "加入模型庫", "Delete Model": "刪除模型", "Load Model": "載入模型", "Model Library": "模型庫",
    # -- common buttons and words --------------------------------------------------------------
    "Apply": "套用", "Reset": "重設", "Update": "更新", "Load": "載入", "Find": "尋找", "Analyze": "分析",
    "Continue": "繼續", "Generate": "產生", "Receive": "接收", "Select...": "選擇⋯", "Select…": "選擇⋯",
    "Choose…": "選擇⋯", "Choose Another…": "選擇其他⋯", "Done": "完成", "Saved": "已儲存", "Save Changes": "儲存變更",
    "Replace Existing": "取代既有", "Insert Example": "插入範例", "Clear Preview": "清除預覽", "Clear Ref": "清除參考",
    "Click End...": "點擊終點⋯", "Cancel Processing": "取消處理", "Reset Roles": "重設角色", "Apply Position": "套用位置",
    "Add Tag": "新增標籤", "New Tag": "新標籤", "Delete Tag": "刪除標籤", "Rename Tag": "重新命名標籤",
    "Rename View": "重新命名視圖", "Rename Overlay": "重新命名疊圖", "Save Overlay": "儲存疊圖", "Rename Data File": "重新命名資料檔",
    "Rename Axis Preset": "重新命名座標軸預設", "Delete Axis Preset": "刪除座標軸預設", "Update View Preset": "更新視圖預設",
    "Select Preset": "選擇預設", "Select View Preset": "選擇視圖預設", "Always on top": "永遠置頂",
    "Active": "作用中", "Inactive": "未作用", "active": "作用中", "Current": "目前", "Both": "兩者", "Lower": "下限",
    "Upper": "上限", "Initial": "初始值", "Fixed": "固定", "Manual": "手動", "Track": "追蹤", "Extrapolate": "外推",
    "Forward": "正向", "Direction": "方向", "Mode": "模式", "Method": "方法", "Format": "格式", "Type": "類型",
    "Unit": "單位", "Role": "角色", "Scope": "範圍", "Region": "區域", "Range": "範圍", "Window": "視窗",
    "Object": "物件", "Operation": "運算", "Category": "類別", "Title": "標題", "Title:": "標題：", "Notes": "備註",
    "Equation": "方程式", "Parameter": "參數", "Index": "索引", "Index:": "索引：", "Output": "輸出", "Resolution": "解析度",
    "Representation": "表示方式", "Prominence": "顯著度", "Marks": "標記", "Panes": "窗格", "Analysis": "分析",
    "End": "終點", "Ref": "參考", "Max:": "最大：", "Min:": "最小：", "Colormap:": "色彩圖：", "Color range:": "色彩範圍：",
    "Transform:": "轉換：", "X Axis:": "X 軸：", "Y Axis:": "Y 軸：", "Line Cut:": "線切：", "Destination:": "目的地：",
    "Output folder:": "輸出資料夾：", "Slice dimensions:": "切片維度：", "Will fix:": "將固定：", "New name:": "新名稱：",
    "Preset name:": "預設名稱：", "Tag name:": "標籤名稱：", "View name:": "視圖名稱：", "Overlay name:": "疊圖名稱：",
    "Name for this axis preset:": "此座標軸預設的名稱：", "New filename (extension is kept):": "新檔名（副檔名保留）：",
    "Sweep (jump to entry):": "Sweep（跳至項目）：", "Current database": "目前資料庫", "Search in": "搜尋範圍",
    "Relative path": "相對路徑", "Function Name": "函式名稱", "Candidate #": "候選 #", "Candidate Type": "候選類型",
    "Candidate type": "候選類型", "Parameter Mismatch": "參數不一致", "No marks": "沒有標記", "No preview": "沒有預覽",
    "No Data": "沒有資料", "No Functions": "沒有函式", "No recent queries": "沒有最近的查詢", "No matching data.": "沒有符合的資料。",
    "No shared parameters": "沒有共用參數", "No location results": "沒有位置結果", "Not connected": "未連線",
    "Not selected": "未選擇", "Pending": "等待中", "Query Results": "查詢結果", "Trace —": "Trace —", "(no data)": "（無資料）",
    "(Index)": "（索引）", "Hidden · click to show": "已隱藏 · 按一下顯示", "Visible · click to hide": "顯示中 · 按一下隱藏",
    "Unexpected error": "未預期的錯誤", "Follow main plot": "跟隨主圖", "Single Trace": "單一 Trace",
    "Trace Colors": "Trace 顏色", "Trace Number": "Trace 編號", "Trace Scope": "Trace 範圍", "Trace separator": "Trace 分隔",
    "Show Data Points": "顯示資料點", "Show values on plot": "在圖上顯示數值", "Show X Cut": "顯示 X 切線",
    "Show Y Cut": "顯示 Y 切線", "X Cut": "X 切線", "Y Cut": "Y 切線", "Unwrap Phase": "相位展開",
    "Unwrapped Phase (deg)": "展開相位（度）", "Unwrapped Phase (rad)": "展開相位（rad）", "Phase (rad)": "相位（rad）",
    "Frequency (GHz)": "頻率（GHz）", "Magnitude |S|": "Magnitude |S|", "Axis Scaling": "座標軸縮放",
    "Frame Information": "畫格資訊", "Playback Speed": "播放速度", "Every trace · 10 ms · 1080p": "每條 Trace · 10 ms · 1080p",
    "Log Channels": "Log 通道", "Step Channels": "Step 通道", "Receiver": "接收端", "IP / host": "IP／主機",
    "Receiver TCP port": "接收端 TCP 連接埠", "IP address or host name of the receiving LabLogViewer": "接收端 LabLogViewer 的 IP 位址或主機名稱",
    "Listen for measurements from another LabLogViewer": "接收另一台 LabLogViewer 傳來的量測",
    "Comment for the selected Data": "選取資料的註解", "Select a data entry to preview it.": "選擇一筆資料以預覽。",
    "No file loaded. File → Open to begin.": "尚未載入檔案。請從 檔案 → 開啟 開始。",
    "Largest data folder (set it in Settings > General)": "最大資料夾（請在 設定 > 一般 設定）",
    "Color mapping for selected 1D traces": "選取的 1D Trace 的色彩對應",
    "Drag the end handles to adjust the shared scientific color range.": "拖曳兩端控制點調整共用的色彩範圍。",
    "Manual marker diameter in pixels": "手動設定標記直徑（像素）", "Copied": "已複製",
    "(click a Log Entry, ↑/↓, or Sweep →)": "（點選 Log 項目、↑/↓ 或 Sweep →）",
    "Plot copied to clipboard.": "圖表已複製到剪貼簿。", "All panes copied to clipboard.": "所有窗格已複製到剪貼簿。",
    "Sharing all panes.": "分享所有窗格。", "Sharing this plot pane.": "分享此圖表窗格。",
    "Choose whether sharing includes the active plot or the current pane layout.": "選擇分享作用中的圖表，或目前整個窗格版面。",
    "No plot is available to copy.": "沒有可複製的圖表。", "No plot is available to share.": "沒有可分享的圖表。",
    "No pane workspace is available to copy.": "沒有可複製的窗格版面。", "Cut unavailable for the active plot": "作用中的圖表無法切線",
    "Blank formula keeps that axis unchanged.": "公式留白則該軸不變。", "blank = x": "留白 = x", "blank = y": "留白 = y",
    "Preview only; Apply updates this 1D pane. Blank means identity.": "僅預覽；按「套用」才更新此 1D 窗格。留白表示不變。",
    "Formula applied to the current displayed X/Y values.": "公式已套用到目前顯示的 X／Y 值。",
    "Formula is available for 1D plots only.": "公式只適用於 1D 圖。",
    "Formula reset; both axes use identity values.": "公式已重設，兩軸都使用原始值。",
    "Saved Formula was invalid; identity was restored.": "儲存的公式無效，已還原為原始值。",
    "Marks are available in 1D and 2D Plot modes": "標記可用於 1D 與 2D 圖模式",
    "No free Point Mark (M1-M10 are occupied).": "沒有空的點標記（M1–M10 都已使用）。",
    "Target: select a Point Mark or Range": "目標：選擇一個點標記或範圍",
    "Select an object to inspect its values.": "選擇一個物件以查看數值。",
    "2D export uses the full valid grid.": "2D 匯出使用完整的有效網格。",
    "Every trace in scope is rendered at 1080p and exported in order; total duration grows with trace count.": "範圍內每條 Trace 以 1080p 依序算圖並匯出；總長度隨 Trace 數增加。",
    "Animation export cancelled.": "已取消匯出動畫。", "Animation export needs at least two traces.": "匯出動畫至少需要兩條 Trace。",
    "Restored previous workspace.": "已還原先前的工作區。", "Opening Database": "正在開啟資料庫",
    "Database required": "需要資料庫", "Database Busy": "資料庫忙碌中", "Preview Busy": "預覽忙碌中",
    "Processing Busy": "處理中", "Preview Failed": "預覽失敗", "Scan failed": "掃描失敗", "Read Failed": "讀取失敗",
    "Load failed": "載入失敗", "Load Failed": "載入失敗", "Export failed": "匯出失敗", "Export Failed": "匯出失敗",
    "Fit failed": "擬合失敗", "Fit Failed": "擬合失敗", "Rename Failed": "重新命名失敗", "Model Load Failed": "模型載入失敗",
    "Plot error": "繪圖錯誤", "2D plot error": "2D 繪圖錯誤", "Slice error": "切片錯誤", "Cannot open file": "無法開啟檔案",
    "Cannot open log": "無法開啟 Log", "Cannot build slice": "無法建立切片", "Cannot build 2D surface": "無法建立 2D 曲面",
    "File Not Found": "找不到檔案", "Channel not found": "找不到通道", "Model Not Found": "找不到模型",
    "Model file not found": "找不到模型檔", "Invalid output": "輸出無效", "Output unavailable": "無法輸出",
    "Output already exists": "輸出檔已存在", "Invalid Tag": "無效的標籤", "Tag already exists": "標籤已存在",
    "Category not changed": "類別未變更", "Resolve category conflicts": "解決類別衝突", "Preset name in use": "預設名稱已被使用",
    "Axis preset unavailable": "座標軸預設無法使用", "Cannot Save Axis Preset": "無法儲存座標軸預設",
    "Cannot Rename Axis Preset": "無法重新命名座標軸預設", "Cannot Delete Axis Preset": "無法刪除座標軸預設",
    "Cannot Update Axis Preset": "無法更新座標軸預設", "Close Viewer First": "請先關閉 Viewer",
    "Replace View Preset?": "取代視圖預設？", "Delete View Preset?": "刪除視圖預設？", "Replace export?": "取代匯出檔？",
    "Incompatible axes": "座標軸不相容", "Different Source Data": "來源資料不同", "Invalid receiver host": "接收端主機無效",
    "Invalid number or out of valid range.": "數字無效或超出範圍。", "Invalid LaTeX": "LaTeX 無效",
    "Automatic Save Failed": "自動儲存失敗", "Automatic Export Failed": "自動匯出失敗", "Source measurement unavailable": "來源量測無法使用",
    "Generated Data not indexed": "產生的資料尚未建立索引", "Full Resolution Safety": "完整解析度安全提醒",
    "Full Resolution may require significant memory and GPU resources.": "完整解析度可能需要大量記憶體與 GPU 資源。",
    "Qt Surface transparency may remain opaque in both the Viewer and exported scene.": "Qt Surface 的透明度在 Viewer 與匯出畫面中可能仍為不透明。",
    "No 3D scene is available for export.": "沒有可匯出的 3D 場景。", "The 3D plot could not be saved.": "無法儲存 3D 圖。",
    "The plot could not be saved.": "無法儲存圖表。", "The plot image could not be saved.": "無法儲存圖表影像。",
    "The plot image could not be prepared for sharing.": "無法準備要分享的圖表影像。",
    "The current N-D view has no export context yet.": "目前的 N 維視圖還沒有可匯出的內容。",
    "Open a Labber log before exporting data.": "匯出資料前請先開啟 Labber log。",
    "Open a Database in the Browser before selecting Data.": "選擇資料前請先在瀏覽器開啟資料庫。",
    "Previous database is unavailable. Open a folder to continue.": "先前的資料庫無法使用，請開啟資料夾以繼續。",
    "Wait for Database loading to finish before renaming a file.": "請等資料庫載入完成再重新命名檔案。",
    "Wait for De-background processing to finish before renaming files.": "請等去背景處理完成再重新命名檔案。",
    "Wait for this Data's Quick Preview to finish, then try again.": "請等此資料的快速預覽完成後再試一次。",
    "Close this Data's Viewer before renaming it so its file handle and saved state stay in sync.": "重新命名前請先關閉此資料的 Viewer，讓檔案與儲存狀態保持一致。",
    "Waiting for Database refresh before opening generated Data…": "等待資料庫更新後再開啟產生的資料⋯",
    "Finishing measurement transfer before closing...": "關閉前正在完成量測傳輸⋯",
    "LabLogViewer started in Safe Recovery Mode. Previous Viewer windows and processing operations were skipped.": "LabLogViewer 以安全復原模式啟動，已略過先前的 Viewer 視窗與處理作業。",
    "Safe Recovery Mode: Database and Browser context restored; previous Viewers were skipped.": "安全復原模式：已還原資料庫與瀏覽器狀態，並略過先前的 Viewer。",
    "LabLogViewer — Recovery Report": "LabLogViewer — 復原報告",
    "Edits are saved to the confirmed native Labber Comment attribute.": "編輯會儲存到確認過的 Labber 原生 Comment 屬性。",
    "A distinct legacy LabLogViewer note is preserved externally. Edits update the native Labber Comment when supported.": "舊版 LabLogViewer 的另一份註解保留在外部；支援時，編輯會更新 Labber 原生 Comment。",
    "Saved native Labber Comment.": "已儲存 Labber 原生 Comment。",
    "That Tag is already available.": "這個標籤已經存在。", "That Tag name already exists.": "這個標籤名稱已經存在。",
    "Choose a different Axis Preset name.": "請使用不同的座標軸預設名稱。", "Delete the selected Axis Preset": "刪除選取的座標軸預設",
    "Rename the selected Axis Preset": "重新命名選取的座標軸預設", "Update the selected Axis Preset": "更新選取的座標軸預設",
    "Delete selected View Preset": "刪除選取的視圖預設", "Update selected View Preset": "更新選取的視圖預設",
    "Saved Overlay axes are unavailable for this Data.": "此資料沒有已儲存疊圖所用的座標軸。",
    "Relative path of the selected Data": "選取資料的相對路徑",
    # -- De-background ------------------------------------------------------------------------------
    "DE-BACKGROUND": "去背景", "COMPATIBILITY": "相容性檢查", "Background B": "背景 B",
    "Complex S parameter": "複數 S 參數", "Select Target and Background Data.": "請選擇目標與背景資料。",
    "Choose both Target and Background Data.": "請選擇目標與背景資料。",
    "Legacy-compatible numeric precision; Labber trace layout is retained.": "與舊版相容的數值精度；保留 Labber 的 Trace 排列。",
    "Waiting for compatibility check.": "等待相容性檢查。", "Could not validate the selected files.": "無法驗證選取的檔案。",
    "Checking S parameters, Frequency grid, and denominator…": "正在檢查 S 參數、頻率網格與分母⋯",
    "Choose a Target and Background with a matching complex S-parameter.": "請選擇具有相同複數 S 參數的目標與背景。",
    "Choose a compatible complex S-parameter.": "請選擇相容的複數 S 參數。",
    "Choose an output path ending in .h5 or .hdf5.": "請選擇以 .h5 或 .hdf5 結尾的輸出路徑。",
    "Compatible. Complex-domain division will use the acquired measurements only.": "相容。複數除法只會使用實際量得的資料。",
    "Complex division is calculated first. Output components use the legacy-compatible precision observed in the supplied Labber _debg file, while preserving the Target dataset dtype and layout.": "先計算複數除法；輸出分量使用與舊版 Labber _debg 檔相同的精度，並保留目標資料集的資料型別與排列。",
    "Complex trace and sweep coordinates do not match.": "複數 Trace 與 Sweep 座標不一致。",
    "Generation is disabled until all compatibility checks pass.": "所有相容性檢查通過前無法產生。",
    "Output cannot replace the Target or Background source file.": "輸出不能取代目標或背景的來源檔。",
    "Processing cancelled. No partial output was kept.": "已取消處理，沒有保留不完整的輸出。",
    "Replace only after explicit confirmation, choose another output, or cancel.": "確認後才會取代；也可以選擇其他輸出或取消。",
    "No compatible complex S-parameter with a named frequency axis and one sweep dimension was found.": "找不到具有頻率軸與單一 Sweep 維度的相容複數 S 參數。",
    "Preparing processing…": "準備處理中⋯", "Cancelling safely…": "正在安全取消⋯", "Cancelling…": "正在取消⋯",
    "Cancelling safely before closing…": "關閉前正在安全取消⋯",
    "Cancelling safely before application shutdown…": "結束程式前正在安全取消⋯",
    "Target": "目標", "Background shape": "背景形狀", "Frequency points": "頻率點數", "Frequency grid": "頻率網格",
    "Frequency range": "頻率範圍", "Denominator": "分母", "S Parameter": "S 參數", "Target Data": "目標資料",
    "Background Data": "背景資料", "Choose...": "選擇⋯",
    # -- YIG analysis -------------------------------------------------------------------------------
    "Fit Model Builder: Ideal Model + Fano + Environment": "擬合模型建構器：理想模型 + Fano + 環境",
    "1. Ideal Model": "1. 理想模型", "2. Parameters (blank initial values/bounds are estimated from data)": "2. 參數（初始值／邊界留白則由資料估計）",
    "3. Optional Model Terms": "3. 選用的模型項", "4. Model Library": "4. 模型庫", "Generated Code": "產生的程式碼",
    "Preview (Auto Guess)": "預覽（自動猜測）", "Preview with Current Data": "以目前資料預覽", "S_ideal =": "S_ideal =",
    "Also generate a |S| model": "同時產生 |S| 模型", "Add to Model Library when saving (equation and notes)": "儲存時加入模型庫（方程式與備註）",
    "Convert units to Hz / s / rad (write expressions in SI units)": "單位換算為 Hz／s／rad（以 SI 單位撰寫）",
    "Define an ideal S-parameter model and optionally include Fano phase and environment terms.": "定義理想 S 參數模型，並可選擇加入 Fano 相位與環境項。",
    "Fano phase rotates only S minus the background; a typical transmission/reflection background is 1.": "Fano 相位只旋轉 S 扣除背景的部分；一般穿透／反射的背景為 1。",
    "Fano phase: S = B + (S_ideal − B)·e^{iθ_F}": "Fano 相位：S = B + (S_ideal − B)·e^{iθ_F}",
    "Environment: A·exp{ i[φ₀ − 2π(w − w_c)τ] }": "環境：A·exp{ i[φ₀ − 2π(w − w_c)τ] }",
    "Delay Reference w_c": "延遲參考 w_c", "Frequency Variable": "頻率變數", "Rebuild LaTeX from Builder Settings": "依建構器設定重建 LaTeX",
    "LaTeX (one equation per line; preview updates above)": "LaTeX（每行一個方程式；上方即時預覽）",
    "Parameter Table (expressions such as pi, pi/2, np.deg2rad(30) are accepted)": "參數表（可使用 pi、pi/2、np.deg2rad(30) 等運算式）",
    "Python-style expression; ^ is converted to ** and i(...) means 1j*(...). Use multiple lines for intermediate variables, with S = ... on the last line. Supported functions include sqrt, exp, sin, cos, log, abs, conj, and pi. LaTeX is also accepted (\\frac{a}{b}, \\sqrt{x}, \\kappa_{e}, \\left|S\\right|). Only math is allowed: imports, file access and other Python code are rejected.": "Python 風格運算式；^ 會轉成 **，i(...) 表示 1j*(...)。中間變數可分多行，最後一行寫 S = ...。支援 sqrt、exp、sin、cos、log、abs、conj 與 pi。也接受 LaTeX（\\frac{a}{b}、\\sqrt{x}、\\kappa_{e}、\\left|S\\right|）。只允許數學：import、檔案存取與其他 Python 程式碼一律拒絕。",
    "i represents the imaginary unit": "i 代表虛數單位", "(created by Model Builder)": "（由模型建構器建立）",
    "Notes: intended use, parameter meanings, etc.": "備註：用途、參數意義等。",
    "For example: applicability, parameter meanings, measurement batch, fitting notes...": "例如：適用範圍、參數意義、量測批次、擬合注意事項⋯",
    "Title (blank uses the function name)": "標題（留白則使用函式名稱）", "Search titles, functions, and notes": "搜尋標題、函式與備註",
    "Choose a saved model and view its equation and notes.": "選擇已儲存的模型以查看方程式與備註。",
    "Copy model files into the library when adding": "加入時把模型檔複製到模型庫",
    "Also delete the model file from the library folder if no other entry uses it": "若沒有其他項目使用，也從模型庫資料夾刪除模型檔",
    "The library is empty. Use Add Current Model or Add from File, or enable Add to Model Library when saving in Model Builder.": "模型庫是空的。請使用「加入目前模型」或「從檔案加入」，或在模型建構器儲存時勾選「加入模型庫」。",
    "Unable to Add Model": "無法加入模型", "Add to Model Library Failed": "加入模型庫失敗", "No Model Loaded": "尚未載入模型",
    "Cannot Load Model": "無法載入模型", "Initial-Guess Warning": "初始猜測警告", "Initial-Guess Function Warning": "初始猜測函式警告",
    "This file was not created by the Model Builder (saved specification not found).": "這個檔案不是由模型建構器建立的（找不到儲存的規格）。",
    "No fitting functions were found in this file.": "這個檔案中沒有擬合函式。",
    "No usable model functions were found (expected at least two parameters: w, p1, ...).": "沒有可用的模型函式（至少需要兩個參數：w、p1⋯）。",
    "The main Analysis window has no model loaded.": "主分析視窗尚未載入模型。",
    "Load data and set a fit range in the main Analysis window first.": "請先在主分析視窗載入資料並設定擬合範圍。",
    "Install the declared SciPy dependency to run numerical fits.": "請安裝 SciPy 才能進行數值擬合。",
    "SciPy unavailable - fit actions disabled": "沒有 SciPy，擬合功能已停用", "Fitting engine: ready": "擬合引擎：就緒",
    "Fitting engine: starting...": "擬合引擎：啟動中⋯", "Fitting...": "擬合中⋯", "Global Fitting...": "全域擬合中⋯",
    "Fitting in a worker process; the Analysis window remains responsive...": "在背景程序擬合，分析視窗仍可操作⋯",
    "Fit Range Too Small": "擬合範圍太小", "Too few frequency points are inside the selected range.": "選取範圍內的頻率點太少。",
    "Fitted values copied to initial values": "擬合值已複製為初始值", "Selected Fit → Initial": "選取的擬合 → 初始值",
    "Shared Values → Parameter Initials": "共用值 → 參數初始值", "Fit T": "擬合 T", "Fit φref": "擬合 φref",
    "Fit-window center": "擬合視窗中心", "Exact Resonance Frequency": "精確共振頻率", "Mean of all resonance-position parameters": "所有共振位置參數的平均",
    "Auto (mean resonance position, otherwise window center)": "自動（共振位置平均，否則為視窗中心）",
    "Bound frequency parameters to fit window": "頻率參數限制在擬合視窗內", "Keep rolling bounds within parameter bounds": "滾動邊界保持在參數邊界內",
    "Rolling parameter tracking (e.g. φ): use the previous value or extrapolation with local bounds.": "滾動參數追蹤（例如 φ）：使用上一個值或外推，並套用局部邊界。",
    "For tracked parameters, the next initial value uses the previous fit (or linear extrapolation).\nBounds are initial value ± range. Expressions such as pi/4 are accepted.": "追蹤的參數下一個初始值使用上一次擬合（或線性外推）。\n邊界 = 初始值 ± 範圍，可使用 pi/4 等運算式。",
    "± Range": "± 範圍", "Global Range": "全域範圍", "Global Fit Role": "全域擬合角色", "Link Mode": "連結模式",
    "Hard link: φ fixed by phase line": "硬連結：φ 由相位線固定", "Soft link: fit φ within a range around line": "軟連結：在相位線附近範圍內擬合 φ",
    "Soft-Link Range": "軟連結範圍", "Phase line estimated": "已估計相位線", "Phase line is not set (T = 0)": "尚未設定相位線（T = 0）",
    "Cannot Estimate Phase Line": "無法估計相位線", "(at least 2 are needed to estimate a line)": "（至少需要 2 個才能估計直線）",
    "Phase period for κ_b sin²φ; the standard period is π.": "κ_b sin²φ 的相位週期；標準週期為 π。",
    "Estimated κ_b in the selected coupling parameter unit; 0 disables it.": "以所選耦合參數單位估計的 κ_b；0 表示停用。",
    "Uncheck if the model parameter is already effective coupling and has no sin²φ factor.": "若模型參數已是有效耦合、沒有 sin²φ 因子，請取消勾選。",
    "κ_eff = coupling parameter × sin²(phase parameter)": "κ_eff = 耦合參數 × sin²(相位參數)", "κ_b (estimated)": "κ_b（估計）",
    "Skip slices near Nodes (weak signal)": "略過 Node 附近的切片（訊號弱）", "Use successful slices only": "只使用成功的切片",
    "Use every Nth eligible slice to reduce runtime.": "每 N 個符合條件的切片取一個以縮短時間。", "Slice Stride": "切片間隔",
    "Maximum objective evaluations; each evaluation includes all selected slices.": "目標函數最大評估次數；每次評估包含所有選取的切片。",
    "Fix shared parameters (use Global Fit or κ_b estimate)": "固定共用參數（使用全域擬合或 κ_b 估計）",
    "When φ is linked to f_m, freeing κ_b and γ_0 per slice can make f_m non-identifiable.\nFixing shared parameters helps constrain the per-slice resonance frequency.": "當 φ 與 f_m 連結時，每個切片都放開 κ_b 與 γ_0 可能使 f_m 無法辨識。\n固定共用參數有助於約束各切片的共振頻率。",
    "Upper bound for the T grid search; adjacent Nodes are separated by 1/(2T).": "T 網格搜尋的上限；相鄰 Node 間隔為 1/(2T)。",
    "T Search Maximum": "T 搜尋上限", "PHASE-LINKED CONTINUOUS FIT": "相位連結連續擬合",
    "Start Phase-Linked Continuous Fit": "開始相位連結連續擬合", "Start Global Linked Fit": "開始全域連結擬合",
    "Run Global Linked Fit": "執行全域連結擬合", "Cannot Start": "無法開始", "Cannot Start Fit": "無法開始擬合",
    "Cannot Start Continuous Fit": "無法開始連續擬合", "Cannot Start Global Linked Fit": "無法開始全域連結擬合",
    "Send Results to Continuous Fit": "將結果送到連續擬合", "Load each per-slice Global Fit result into Continuous Fit for review.": "把每個切片的全域擬合結果載入連續擬合以檢視。",
    "Global Linked Fit results sent to Continuous Fit for per-slice review": "全域連結擬合結果已送到連續擬合以逐切片檢視",
    "Copied Global Linked Fit shared values to initial values": "已將全域連結擬合的共用值複製為初始值",
    "The current model parameters differ from the Global Linked Fit.": "目前的模型參數與全域連結擬合不同。",
    "The current model parameters differ from this Continuous Fit result.": "目前的模型參數與此連續擬合結果不同。",
    "All Parameters": "所有參數", "Single Parameter": "單一參數", "Preview Selected Slice": "預覽選取的切片",
    "Window 1 follows Tracking Parameter 1 using the current fit-window width.\nOptional Window 2 follows Tracking Parameter 2 with a fixed width and offset.\nWhen enabled, fits use the union of both windows; the first slice uses the parameter-table initial values.": "視窗 1 以目前擬合視窗寬度跟隨追蹤參數 1。\n選用的視窗 2 以固定寬度與偏移跟隨追蹤參數 2。\n啟用時擬合使用兩個視窗的聯集；第一個切片使用參數表的初始值。",
    "Window 2 Offset": "視窗 2 偏移", "Window 2 Width": "視窗 2 寬度", "Trajectory half-width": "軌跡半寬",
    "Trajectory window half-width": "軌跡視窗半寬", "Sweep Parameter": "Sweep 參數", "Sweep Parameter Value": "Sweep 參數值",
    "Sweep Index (0-based)": "Sweep 索引（從 0 開始）", "Data and a frequency-valued tracking parameter are required": "需要資料與以頻率為單位的追蹤參數",
    "Excluded frequency ranges (GHz), e.g. 3.0564-3.0569, 3.0528-3.0532": "排除的頻率範圍（GHz），例如 3.0564-3.0569, 3.0528-3.0532",
    "Dip candidate frequencies (GHz), e.g. 4.26, 4.59, 4.93": "凹陷候選頻率（GHz），例如 4.26, 4.59, 4.93",
    "Additional points excluded on each side of a detected spike.": "偵測到的尖峰兩側額外排除的點數。",
    "Half-width of the rolling median window.": "滾動中位數視窗的半寬。", "Outlier threshold in local-noise standard deviations.": "離群值門檻（以局部雜訊標準差計）。",
    "Ignored saved fitting state for a different Data source.": "已忽略來自其他資料來源的擬合狀態。",
    "The analysis window uses a read-only snapshot of its source Viewer Data.": "分析視窗使用來源 Viewer 資料的唯讀快照。",
    "Data is owned by the source Viewer. Select another Data there to open a new analysis window.": "資料屬於來源 Viewer；請在那裡選擇其他資料以開啟新的分析視窗。",
    "Estimator Source": "估計來源", "Detection Mode": "偵測模式", "Enable Coarse Detector": "啟用粗略偵測器",
    "Open Coarse Detector": "開啟粗略偵測器", "Run Coarse Detection": "執行粗略偵測", "Coarse Detector (empirical fallback)": "粗略偵測器（經驗備援）",
    "Disabled. Coarse candidates are empirical and are not physical extrema.": "已停用。粗略候選是經驗結果，不是物理極值。",
    "Enabled. Results will be labeled as coarse candidates.": "已啟用。結果會標示為粗略候選。",
    "Cannot Detect Coarse Nodes": "無法偵測粗略 Node", "Coarse detection cancelled; no partial result applied.": "已取消粗略偵測，沒有套用部分結果。",
    "Coarse detection needs exactly one unambiguous active sweep axis.": "粗略偵測需要剛好一個明確的作用中 Sweep 軸。",
    "Cancelling coarse detection…": "正在取消粗略偵測⋯", "Running empirical coarse detection…": "正在執行經驗式粗略偵測⋯",
    "Run physical or coarse analysis first.": "請先執行物理分析或粗略分析。", "Effective threshold: median dip depth": "有效門檻：凹陷深度中位數",
    "Manual dip-depth threshold": "手動凹陷深度門檻", "Local minima below threshold × the 90th percentile are treated as dip candidates.": "低於「門檻 × 第 90 百分位數」的局部極小值視為凹陷候選。",
    "Minimum distance": "最小距離", "Minimum sweep distance": "最小 Sweep 距離", "Smoothing points": "平滑點數",
    "Analysis cancelled. No result was applied.": "已取消分析，沒有套用結果。", "Analysis target was deleted.": "分析目標已被刪除。",
    "Loading the selected Data Model and analyzing…": "正在載入選取的資料模型並分析⋯",
    "Preparing complex traces from the source Viewer…": "正在從來源 Viewer 準備複數 Trace⋯",
    "Half-Peak requires a Magnitude or Magnitude + dB trace.": "半峰需要 Magnitude 或 Magnitude + dB Trace。",
    "This Data has multiple or no active sweep dimensions; the current analyzer requires one.": "此資料有多個或沒有作用中的 Sweep 維度；目前的分析器只接受一個。",
    "The selected complex sweep is not available.": "選取的複數 Sweep 無法使用。", "Select a target, then Find.": "請選擇目標，再按「尋找」。",
    "Ready. Press Find to analyze this local region.": "就緒。按「尋找」分析這個局部區域。",
    "Review the Auto Region preview, then press Find again.": "請檢查自動區域預覽，再按一次「尋找」。",
    "Preview Region": "預覽區域", "Magnitude, Re, Im": "Magnitude、Re、Im", "Reduced χ²": "約化 χ²",
    "R² (complex)": "R²（複數）", "R² (magnitude)": "R²（Magnitude）", "T_avg |S|": "T_avg |S|",
    "Conjugate output (for reversed IQ rotation)": "輸出共軛（用於反向 IQ 旋轉）",
    "'IQ Transform' is reserved for the built-in preset.": "「IQ Transform」保留給內建預設使用。",
    "Blank uses fit_results beside the source Data.": "留白則使用來源資料旁的 fit_results。",
    "Roles: resonance positions are initialized from the data dip and tracked-window center; linewidth/coupling values use the estimated half-width; other values use unit-based defaults.": "角色：共振位置由資料凹陷與追蹤視窗中心初始化；線寬／耦合值使用估計的半寬；其他值使用依單位的預設值。",
    "Save and Load": "儲存與載入", "Equation:": "方程式：",
    # -- 3D and Viewer toolbars --------------------------------------------------------------------
    "3D Surface": "3D Surface", "Surface": "曲面", "Transparent Surface": "透明曲面", "Dual Surface": "雙曲面",
    "Waterfall": "瀑布圖", "Trajectory": "軌跡", "Scatter": "散點圖", "orthographic": "正交", "perspective": "透視",
    "Channel Browser  (no file loaded)": "通道瀏覽器（尚未載入檔案）",
    "(no remaining dimensions - full X/Y coverage)": "（沒有其他維度：已完整涵蓋 X／Y）",
    "Resolution:": "解析度：", "Along X": "沿 X", "Along Y": "沿 Y", "Waterfall spacing": "瀑布間距",
    # -- Network / sharing ---------------------------------------------------------------------------
    "Choose Mark": "選擇標記", "Choose an S parameter and run the analysis.": "請選擇 S 參數並執行分析。",
    "Enter at least one coordinate.": "請至少輸入一個座標。", "FAIL": "失敗", "all": "全部", "auto": "自動",
    "hard": "硬連結", "soft": "軟連結", "to": "到", "window": "視窗", "linear": "線性",
    # -- found by opening every window in Chinese ------------------------------------------------
    "&Export": "匯出(&E)", "&Show": "顯示(&S)", "Export...": "匯出⋯", "Network Workspace...": "網路工作區⋯",
    "LabLogViewer Help...": "LabLogViewer 說明⋯", "De-background": "去背景",
    "(2D data - switch to 1D Plot mode, or use a Line Cut, to view a table)": "（2D 資料：請切換到 1D 圖模式，或使用線切，才能查看表格）",
    "1 Pane": "1 個窗格", "2 Panes · Side by Side": "2 個窗格 · 左右", "2 Panes · Stacked": "2 個窗格 · 上下",
    "3 Panes": "3 個窗格", "4 Panes · 2 × 2": "4 個窗格 · 2 × 2", "= Window 1": "= 視窗 1",
    "FORMULA": "公式", "PLOT SETTINGS": "繪圖設定", "MARKS": "標記", "LOCAL ANALYSIS": "局部分析",
    "VIEW PRESET": "視圖預設", "TRACES": "Trace", "Axis Preset": "座標軸預設", "Transform": "轉換",
    "X Axis": "X 軸", "Y Axis": "Y 軸", "Identity transformation": "不轉換", "Magnitude (dB)": "Magnitude（dB）",
    "Drop a measurement here to send": "把量測拖到這裡傳送", "Scanning HDF5 files...": "正在掃描 HDF5 檔案⋯",
    "Target: Select a 1D Point Mark or Range": "目標：選擇 1D 點標記或範圍", "Target: select a visible Point Mark": "目標：選擇可見的點標記",
    "κ_eff = κ_b sin²φ (recommended)": "κ_eff = κ_b sin²φ（建議）", "✓ Generated model code is valid.": "✓ 產生的模型程式碼有效。",
    "Phase Parameter φ": "相位參數 φ",
    "Skipped or failed slices do not update tracking. The fit extrapolates across weak-signal Nodes.": "略過或失敗的切片不更新追蹤；擬合會外推跨越訊號弱的 Node。",
    "The phase is modeled as linear in resonance frequency. For κm = κb sin²φ, φ = nP is a physical Node and φ = (n + 1/2)P is a physical Antinode.": "相位以共振頻率的線性函數建模。對 κm = κb sin²φ，φ = nP 為物理 Node，φ = (n + 1/2)P 為物理 Antinode。",
    "Input comes from the current Continuous Fit results, including fit windows and preprocessing.\nRoles: Phase Line, per-slice, shared, or fixed.": "輸入來自目前的連續擬合結果，包含擬合視窗與前處理。\n角色：相位線、每切片、共用或固定。",
    "Workflow: Continuous Fit → estimate the phase line → Global Linked Fit → optional phase-linked Continuous Fit.\nA single trace identifies κ_eff = κ_b sin²φ only. The κ estimator cannot distinguish T from −T; it reports the positive convention.": "流程：連續擬合 → 估計相位線 → 全域連結擬合 → 選用的相位連結連續擬合。\n單一 Trace 只能辨識 κ_eff = κ_b sin²φ。κ 估計器無法區分 T 與 −T，採用正值慣例。",
    # pyqtgraph plot menus
    "View All": "顯示全部", "X axis": "X 軸", "Y axis": "Y 軸", "Mouse Mode": "滑鼠模式", "3 button": "三鍵", "1 button": "單鍵",
    "Plot Options": "繪圖選項", "Transforms": "轉換", "Downsample": "降採樣", "Alpha": "透明度",
    "Grid": "格線", "Auto Pan Only": "僅自動平移", "Visible Data Only": "僅可見資料", "Invert Axis": "反轉座標軸",
    "Mouse Enabled": "啟用滑鼠", "Link Axis:": "連結座標軸：", "Log X": "X 對數", "Log Y": "Y 對數", "Power Spectrum (FFT)": "功率譜（FFT）",
    "Subtract Mean": "減去平均", "Clip to View": "裁切至視圖", "Subsample": "子取樣", "Max Traces:": "最多曲線：",
    "Forget hidden traces": "清除隱藏的曲線", "Show X Grid": "顯示 X 格線", "Show Y Grid": "顯示 Y 格線", "Auto": "自動",
    "Manual": "手動", "Export": "匯出", "Plot Options...": "繪圖選項⋯",
    "Automatically downsample data based on the visible range. This assumes X values are uniformly spaced.": "依可見範圍自動降採樣（假設 X 等間距）。",
    "Plot only the portion of each curve that is visible. This assumes X values are uniformly spaced.": "只繪製曲線可見的部分（假設 X 等間距）。",
    "Downsample data before plotting. (plot every Nth sample)": "繪圖前降採樣（每 N 個取一個）。",
    "Downsample by taking the first of N samples. This method is fastest and least accurate.": "每 N 個樣本取第一個；最快但最不精確。",
    "Downsample by taking the mean of N samples.": "每 N 個樣本取平均。",
    "Downsample by drawing a saw wave that follows the min and max of the original data. This method produces the best visual representation of the data but is slower.": "以跟隨原資料最大／最小值的鋸齒波降採樣；外觀最接近原資料但較慢。",
    "Display averages of the curves displayed in this plot. The parameter list allows you to choose parameters to average over (if any are available).": "顯示此圖中曲線的平均；可從參數清單選擇要平均的參數（若有）。",
    "If multiple curves are displayed in this plot, check this box to limit the number of traces that are displayed.": "若此圖顯示多條曲線，勾選以限制顯示的數量。",
    "If multiple curves are displayed in this plot, check \"Max Traces\" and set this value to limit the number of traces that are displayed.": "若此圖顯示多條曲線，勾選「最多曲線」並設定此值以限制顯示數量。",
    "If MaxTraces is checked, remove curves from memory after they are hidden (saves memory, but traces can not be un-hidden).": "勾選「最多曲線」時，隱藏的曲線會從記憶體移除（省記憶體，但無法再顯示）。",
    # matplotlib toolbar
    "Home": "初始視圖", "Back": "上一步", "Pan": "平移", "Zoom": "縮放", "Subplots": "子圖",
    "Customize": "自訂", "Save": "儲存", "Reset original view": "重設為原始視圖", "Back to previous view": "回到上一個視圖",
    "Forward to next view": "前往下一個視圖", "Left button pans, Right button zooms\nx/y fixes axis, CTRL fixes aspect": "左鍵平移，右鍵縮放\nx/y 固定軸，CTRL 固定比例",
    "Zoom to rectangle\nx/y fixes axis": "框選縮放\nx/y 固定軸", "Configure subplots": "設定子圖",
    "Edit axis, curve and image parameters": "編輯座標軸、曲線與影像參數", "Save the figure": "儲存圖形",
}

# English template with {} -> Chinese template with {0} {1} ... in the English order
PATTERNS = [
    ("'{}' already exists. Replace it?", "「{0}」已存在，要取代嗎？"),
    ("'{}' uses a channel or axis that is not present in this file.", "「{0}」使用了此檔案中沒有的通道或座標軸。"),
    ("'{}' and '{}' cannot be plotted against each other — they vary over different things (e.g. one is a per-sweep-entry value, the other varies within a single trace). Pick two axes from the same domain.",
     "「{0}」與「{1}」無法互相作圖——它們隨不同的量變化（例如一個是每個 Sweep 項目的值，另一個在單一 Trace 內變化）。請選擇同一個範疇的兩個軸。"),
    ("(entry {})", "（項目 {0}）"), ("({} could not be parsed)", "（{0} 無法解析）"),
    ("3D LOD preparation failed: {}", "3D LOD 準備失敗：{0}"), ("3D Surface — {}", "3D Surface — {0}"),
    ("3D export failed: {}", "3D 匯出失敗：{0}"), ("3D publication export failed: {}", "3D 出版品質匯出失敗：{0}"),
    ("3D sharing failed: {}", "3D 分享失敗：{0}"),
    ("A View Preset named '{}' already exists for this Data. Replace it?", "此資料已有名為「{0}」的視圖預設，要取代嗎？"),
    ("Active Pane: {}", "作用中窗格：{0}"), ("Active: Trace {}", "作用中：Trace {0}"),
    ("Added excluded range {}–{} GHz", "已加入排除範圍 {0}–{1} GHz"),
    ("Added {} to the Model Library; its equation and notes can be edited there.", "已將 {0} 加入模型庫，可在那裡編輯方程式與備註。"),
    ("Along X ({})", "沿 X（{0}）"), ("Along Y ({})", "沿 Y（{0}）"),
    ("Analysis unavailable: {}", "無法分析：{0}"), ("Animation encoding failed: {}", "動畫編碼失敗：{0}"),
    ("Animation exported: {}", "動畫已匯出：{0}"), ("Axis Preset '{}' deleted.", "已刪除座標軸預設「{0}」。"),
    ("Axis Preset '{}' updated.", "已更新座標軸預設「{0}」。"),
    ("Bundled fitting model unavailable ({}): {}", "內建擬合模型無法使用（{0}）：{1}"),
    ("Channel Browser — {}", "通道瀏覽器 — {0}"), ("Checking {} compatibility…", "正在檢查 {0} 相容性⋯"),
    ("Coarse detection failed: {}", "粗略偵測失敗：{0}"), ("Complete: {} ({} s)", "完成：{0}（{1} s）"),
    ("Continuous Fit {}: {} slices, {} successful, {} s", "連續擬合 {0}：{1} 個切片，成功 {2} 個，{3} s"),
    ("Continuous Fit: {}/{} ({} successful), {} s", "連續擬合：{0}/{1}（成功 {2} 個），{3} s"),
    ("Copied fitted values from slice #{} to initial values", "已將切片 #{0} 的擬合值複製為初始值"),
    ("Could not build this 2D surface:\n\n{}", "無法建立此 2D 曲面：\n\n{0}"),
    ("Could not build this slice:\n\n{}", "無法建立此切片：\n\n{0}"),
    ("Could not plot this selection:\n\n{}", "無法繪製此選取：\n\n{0}"),
    ("Could not scan this folder:\n\n{}", "無法掃描此資料夾：\n\n{0}"),
    ("Current: {}", "目前：{0}"), ("Database metadata ready — {} logs", "資料庫中繼資料已就緒 — {0} 個 log"),
    ("Database usable — enriching metadata for {} files...", "資料庫可使用 — 正在補充 {0} 個檔案的中繼資料⋯"),
    ("Database: {}", "資料庫：{0}"), ("Database: {}  —  {} logs", "資料庫：{0}  —  {1} 個 log"),
    ("De-background completed.\n{}", "去背景完成。\n{0}"), ("De-background created: {}; refreshing Database…", "已產生去背景：{0}；正在更新資料庫⋯"),
    ("De-background failed.\n{}", "去背景失敗。\n{0}"), ("Delete '{}' for this Data?", "刪除此資料的「{0}」？"),
    ("Delete '{}' from the library?", "從模型庫刪除「{0}」？"), ("Delete '{}'?", "刪除「{0}」？"),
    ('Delete Tag "{}"?\n\n{}Deleting it will remove the Tag from those entries.', "刪除標籤「{0}」？\n\n{1}刪除後這些項目的此標籤也會移除。"),
    ("Detected {} Coarse Node Candidates", "偵測到 {0} 個粗略 Node 候選"), ("Effective threshold: {}", "有效門檻：{0}"),
    ("End [{}]", "終點 [{0}]"), ("Start [{}]", "起點 [{0}]"), ("Exported scientific data: {}", "已匯出科學資料：{0}"),
    ("Exported {} and parameter plot PNG", "已匯出 {0} 與參數圖 PNG"), ("Exported {} location results to {}", "已匯出 {0} 筆位置結果到 {1}"),
    ("Exported {} with _phase.png and _report.txt", "已匯出 {0}，含 _phase.png 與 _report.txt"),
    ("Failed to open file:\n\n{}", "無法開啟檔案：\n\n{0}"), ("Fit complete: R² = {}, nfev = {}, {} s", "擬合完成：R² = {0}，nfev = {1}，{2} s"),
    ("GIF exported: {} traces, {} frames, 10 ms/frame, {} s total", "GIF 已匯出：{0} 條 Trace，{1} 幀，每幀 10 ms，共 {2} s"),
    ("Global Linked Fit complete: χ²_red = {}, {} s", "全域連結擬合完成：χ²_red = {0}，{1} s"),
    ("Global Linked Fit running: {} slices", "全域連結擬合進行中：{0} 個切片"),
    ("Global Linked Fit running: {} slices, {} points...", "全域連結擬合進行中：{0} 個切片，{1} 點⋯"),
    ("Initial values updated (source: {})", "初始值已更新（來源：{0}）"), ("LabLogViewer v{}", "LabLogViewer v{0}"),
    ("LabLogViewer v{} — Database Browser", "LabLogViewer v{0} — 資料庫瀏覽器"), ("LabLogViewer v{} — {}", "LabLogViewer v{0} — {1}"),
    ("Largest data folder: {}", "最大資料夾：{0}"), ("Listening on port {}", "正在監聽連接埠 {0}"),
    ("Loaded Continuous Fit Results: {} slices", "已載入連續擬合結果：{0} 個切片"), ("Loaded View Preset: {}", "已載入視圖預設：{0}"),
    ("Loaded model: {} functions", "已載入模型：{0} 個函式"), ("Loaded {}", "已載入 {0}"),
    ("Loaded {}: {}–{} GHz, {} points, {} traces", "已載入 {0}：{1}–{2} GHz，{3} 點，{4} 條 Trace"),
    ("Loaded: {}  ({})", "已載入：{0}（{1}）"), ("Maximum of {} Marks reached.", "已達標記上限 {0} 個。"),
    ("Measurement stored externally: {}", "量測已儲存在外部：{0}"), ("Metadata enrichment failed: {}", "補充中繼資料失敗：{0}"),
    ("Model file not found ({}); using the bundled model of the same name.", "找不到模型檔（{0}）；改用同名的內建模型。"),
    ("Moving {} to {} conflicts with existing per-Data assignments. Replace the conflicting single-select assignments explicitly?",
     "把 {0} 移到 {1} 會與既有的單筆指定衝突，要明確取代衝突的單選指定嗎？"),
    ("Node / Antinode Finder — {}", "Node／Antinode 尋找器 — {0}"),
    ("Overlay active · {} traces\nActive: Trace {}", "疊圖中 · {0} 條 Trace\n作用中：Trace {1}"),
    ("Pane {}", "窗格 {0}"), ("Pane {} · {}", "窗格 {0} · {1}"), ("Parameter {}", "參數 {0}"),
    ("Partial acquisition: {} / {} sweeps shown ({}).", "部分擷取：顯示 {0} / {1} 個 Sweep（{2}）。"),
    ("Preparing Viewer Data: {}", "正在準備 Viewer 資料：{0}"), ("Preview: {} to {}", "預覽：{0} 到 {1}"),
    ("Receive failed: {}", "接收失敗：{0}"), ("Received: {}", "已接收：{0}"), ("Renamed Data file to {}", "資料檔已重新命名為 {0}"),
    ("Rendered {} traces; skipped {} incompatible trace(s).", "已算圖 {0} 條 Trace；略過 {1} 條不相容的 Trace。"),
    ("Rendering frame {} / {}", "正在算圖第 {0} / {1} 幀"), ("Saved External Comment ({}).", "已儲存外部註解（{0}）。"),
    ("Saved external Comment ({}).", "已儲存外部註解（{0}）。"), ("Saved View Preset: {}", "已儲存視圖預設：{0}"),
    ("Saved plot image: {}", "已儲存圖表影像：{0}"), ("Saved {}", "已儲存 {0}"), ("Saved {} and {}", "已儲存 {0} 與 {1}"),
    ("Scanning HDF5 files...\n{} / {}", "正在掃描 HDF5 檔案⋯\n{0} / {1}"),
    ("Select the active sweep axis ({}) before running the Coarse Detector.", "執行粗略偵測器前請先選擇作用中的 Sweep 軸（{0}）。"),
    ("Skip window ≈ Node ± {} MHz (about {}% of the frequency span); here sin²φ < {}", "略過視窗 ≈ Node ± {0} MHz（約頻寬的 {1}%）；此處 sin²φ < {2}"),
    ("Tags: {}", "標籤：{0}"), ("The Database refresh did not find the generated log:\n\n{}", "資料庫更新後找不到產生的 log：\n\n{0}"),
    ("The data could not be exported:\n\n{}", "無法匯出資料：\n\n{0}"),
    ("The generated file is no longer available:\n\n{}", "產生的檔案已不存在：\n\n{0}"),
    ("The model file no longer exists:\n{}\n\nChoose the model again (Load Model .py or Model Library).",
     "模型檔已不存在：\n{0}\n\n請重新選擇模型（載入模型 .py 或模型庫）。"),
    ("The output file already exists:\n{}", "輸出檔已存在：\n{0}"),
    ("The requested surface contains {} points. Continue with the full mesh?", "要求的曲面有 {0} 個點，要使用完整網格繼續嗎？"),
    ("This file could not be parsed as a Labber measurement log:\n\n{}\n\n(Raw HDF5 Explorer Mode fallback is not implemented yet in this phase.)",
     "此檔案無法解析為 Labber 量測 log：\n\n{0}\n\n（原始 HDF5 瀏覽模式尚未實作。）"),
    ("This file could not be parsed:\n\n{}", "此檔案無法解析：\n\n{0}"),
    ("This result was created from {}, not the currently loaded Data. Load the matching Data to view fit plots.",
     "此結果來自 {0}，不是目前載入的資料。請載入對應的資料以查看擬合圖。"),
    ("Trace {} / {}{}", "Trace {0} / {1}{2}"), ("Transfer failed: {}", "傳輸失敗：{0}"), ("Transferring {} / {} bytes", "正在傳輸 {0} / {1} 位元組"),
    ("Unsupported frequency unit: {}", "不支援的頻率單位：{0}"), ("Updated View Preset: {}", "已更新視圖預設：{0}"),
    ("Waterfall: {} traces; {} display vertices; frequency features retained by extrema/curvature selection.",
     "瀑布圖：{0} 條 Trace；{1} 個顯示頂點；以極值／曲率選取保留頻率特徵。"),
    ("YIG Mirror Analysis - {}", "YIG 鏡像分析 - {0}"), ("{}\n\nSave anyway?", "{0}\n\n仍要儲存嗎？"),
    ("{}\nX / Start: {}\nY / End: {}\nValue / Delta: {}", "{0}\nX／起點：{1}\nY／終點：{2}\n值／差：{3}"),
    ("{} - {}\nDelta {}", "{0} - {1}\n差 {2}"), ('{} Tag assigned to "{}"', "已將 {0} 標籤指定給「{1}」"),
    ("{} coarse candidates detected. These are empirical, not physical.", "偵測到 {0} 個粗略候選；這些是經驗結果，不是物理結果。"),
    ("{} encoding is unavailable in this installation.", "此安裝不支援 {0} 編碼。"),
    ("{} objects ({} / {} Point Marks)", "{0} 個物件（{1} / {2} 個點標記）"),
    ("{} points excluded in this slice's fit range", "此切片擬合範圍內排除了 {0} 點"), ("{} px", "{0} px"),
    ("{} selected · {} visible", "已選 {0} · 顯示 {1}"), ("{} slices will be used", "將使用 {0} 個切片"),
    ("{} traces · {}–{} · Active: {}", "{0} 條 Trace · {1}–{2} · 作用中：{3}"), ("{} traces/s", "{0} 條 Trace/s"),
    ("{} unavailable", "{0} 無法使用"), ("{} unavailable for the active plot", "作用中的圖表無法使用 {0}"),
    ("{} vs {} — {} rows{}", "{0} 對 {1} — {2} 列{3}"),
    ("{}: {} Node Candidates, {} Antinode Candidates; fit used {} of {} traces.", "{0}：{1} 個 Node 候選、{2} 個 Antinode 候選；擬合使用 {4} 條中的 {3} 條 Trace。"),
    ("{}: {} rendered samples / {} source points. Point rendering is capped at 20,000 samples.", "{0}：{1} 個算圖樣本 / {2} 個來源點。點的算圖上限為 20,000 個樣本。"),
    ("{}: {} rendered samples from {} source points.", "{0}：由 {2} 個來源點算圖 {1} 個樣本。"),
    ("{}continuous fit running: {} slices ({} → {})", "{0}連續擬合進行中：{1} 個切片（{2} → {3}）"),
    ("Function: {}    File: {}{}\nParameters: {}\nCreated: {}    Updated: {}", "函式：{0}    檔案：{1}{2}\n參數：{3}\n建立：{4}    更新：{5}"),
    ("nfev = {}   cost = {}   {} s", "nfev = {0}   cost = {1}   {2} s"),
    ("{} result{} · {}:", "{0} 筆結果 · {2}："),
    ("Loading {}...", "正在載入 {0}⋯"), ("Tags - {}", "標籤 - {0}"), ("Output folder: {}", "輸出資料夾：{0}"), ("Will fix: {}", "將固定：{0}"),
    ("Track {}", "追蹤 {0}"), ("X Cut @ {}", "X 切線 @ {0}"), ("Y Cut @ {}", "Y 切線 @ {0}"), ("X Cut — {}", "X 切線 — {0}"),
    ("Y Cut — {}", "Y 切線 — {0}"), ("{} points", "{0} 點"),
    ("Window width {} MHz, {} slices, offset {} MHz\nWindow follows: {}", "視窗寬度 {0} MHz，{1} 個切片，偏移 {2} MHz\n視窗跟隨：{3}"),
    ("{} selected · {} visible\nActive: Trace {}", "已選 {0} · 顯示 {1}\n作用中：Trace {2}"),
]
